# Especialização em Ciência de Dados - Turma 2018.1 - Facens
## Projeto em Ciência de Dados Trabalho 1 – Análise Exploratória 


|**Professor:**|Fernando Vieira da Silva, M.Sc.|
|-----|-----------------------------------|

|**Nome:**|José Diniz Junior            |**RA:**|183134|
|-----|-----------------------------|---|------|
|**Nome:**|Roberto Leonardo Rodrigues   |**RA:**|060235|

O objetivo deste trabalho é explorar e entender melhor as características dos dados que serão utilizados durante o Trabalho de Conclusão do Curso. Use os conhecimentos adquiridos nas disciplinas de Visualização de Dados, Estatística e Programação em Python para Ciência de Dados. Dica: aproveite essa oportunidade para tirar suas próprias dúvidas sobre os dados e conhecer melhor o problema que você escolheu estudar. Este trabalho deve ser entregue em forma de um notebook Jupyter.

1 – Observe os dados inconsistentes. Quais campos possuem registros faltantes? (Zero, vazio, negativo, NaN, etc). Quais possuem valores fora da faixa esperada? (ex: em um dataset com dados de pessoas, há registros de altura maior que 2,5m?). Qual a proporção em relação aos dados corretos? Para cada uma das campos com dados faltantes, qual sua proposta para tratar os dados? (ex: pretende preencher de alguma forma? Se sim, como?) (3 pontos)

In [16]:
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
import numpy as np
#import plotly.plotly as py
from plotly import tools
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

In [17]:
dfFT = pd.read_csv('Fotovoltaico.csv', encoding='utf-8', quotechar='"')
dfFT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684450 entries, 0 to 684449
Data columns (total 9 columns):
data             684450 non-null object
painel           670431 non-null float64
energia_dia      669954 non-null float64
energia_ano      669954 non-null float64
energia_total    669954 non-null float64
potencia         669954 non-null float64
power_led        684450 non-null int64
solarnet_led     684450 non-null int64
solarweb_led     684450 non-null int64
dtypes: float64(5), int64(3), object(1)
memory usage: 47.0+ MB

In [49]:
data2 = (dfFT < 0).sum().drop('data')
data2

painel           0
energia_dia      0
energia_ano      0
energia_total    0
potencia         0
power_led        0
solarnet_led     0
solarweb_led     0
dtype: int64

In [50]:
data3 = (dfMT < 0).sum().drop('data')
data3

deficit_vapor_vmin         0
deficit_vapor_vmedio       0
ponto_orvalho_vmin         0
ponto_orvalho_vmedio       0
precipitacao_valor         0
radiacao_solar_valor       0
temperatura_ar_vmin        0
temperatura_ar_vmedio      0
temperatura_ar_vmax        0
umidade_ar_vmin            0
umidade_ar_vmedio          0
umidade_ar_vmax            0
velocidade_vento_vmedio    0
velocidade_vento_vmax      0
dtype: int64

In [37]:
dfFT.describe()

,painel,energia_dia,energia_ano,energia_total,potencia,power_led,solarnet_led,solarweb_led
count,670431.000000,669954.000000,6.699540e+05,6.699540e+05,669954.000000,684450.000000,684450.000000,684450.000000
mean,2.499896,24054.271769,1.434321e+07,4.970747e+07,2300.205275,0.979798,0.979798,0.979798
std,1.118366,24335.027877,2.760229e+06,9.130962e+06,3652.541291,0.140690,0.140690,0.140690
min,1.000000,0.000000,9.974486e+06,3.671850e+07,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,1.120244e+07,3.794650e+07,0.000000,1.000000,1.000000,1.000000
50%,2.000000,16735.000000,1.425701e+07,4.847110e+07,0.000000,1.000000,1.000000,1.000000
75%,4.000000,45940.000000,1.719769e+07,6.183590e+07,3647.000000,1.000000,1.000000,1.000000
max,4.000000,79350.000000,1.928078e+07,6.391900e+07,20256.000000,1.000000,1.000000,1.000000

In [38]:
dfFT.head()

,data,painel,energia_dia,energia_ano,energia_total,potencia,power_led,solarnet_led,solarweb_led
0,2018-09-30 23:58:56.970,2.0,31640.0,14760184.0,48471100.0,0.0,1,1,1
1,2018-09-30 23:58:53.120,4.0,30504.0,11202444.0,37946500.0,0.0,1,1,1
2,2018-09-30 23:58:49.283,1.0,42950.0,19280784.0,63919004.0,0.0,1,1,1
3,2018-09-30 23:58:40.173,3.0,43730.0,15342723.0,51709800.0,0.0,1,1,1
4,2018-09-30 23:58:36.377,2.0,31640.0,14760184.0,48471100.0,0.0,1,1,1

In [18]:
dfMT = pd.read_csv('Meteorologia.csv', encoding='utf-8', quotechar='"')
dfMT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4297 entries, 0 to 4296
Data columns (total 15 columns):
data                       4297 non-null object
deficit_vapor_vmin         4297 non-null float64
deficit_vapor_vmedio       4297 non-null float64
ponto_orvalho_vmin         4297 non-null float64
ponto_orvalho_vmedio       4297 non-null float64
precipitacao_valor         4297 non-null float64
radiacao_solar_valor       4297 non-null float64
temperatura_ar_vmin        4297 non-null float64
temperatura_ar_vmedio      4297 non-null float64
temperatura_ar_vmax        4297 non-null float64
umidade_ar_vmin            4297 non-null float64
umidade_ar_vmedio          4297 non-null float64
umidade_ar_vmax            4297 non-null float64
velocidade_vento_vmedio    4297 non-null float64
velocidade_vento_vmax      4297 non-null float64
dtypes: float64(14), object(1)
memory usage: 503.6+ KB

In [40]:
dfMT.describe()

,deficit_vapor_vmin,deficit_vapor_vmedio,ponto_orvalho_vmin,ponto_orvalho_vmedio,precipitacao_valor,radiacao_solar_valor,temperatura_ar_vmin,temperatura_ar_vmedio,temperatura_ar_vmax,umidade_ar_vmin,umidade_ar_vmedio,umidade_ar_vmax,velocidade_vento_vmedio,velocidade_vento_vmax
count,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000
mean,0.897098,0.912234,13.781941,13.871841,0.021131,160.484524,20.504631,20.597866,20.695986,68.827389,69.273230,69.724329,0.461089,0.554689
std,0.873278,0.887208,3.273901,3.245847,0.183947,253.018622,5.225928,5.262248,5.300486,19.414074,19.229212,19.057480,0.558024,0.614450
min,0.050000,0.050000,2.900000,3.400000,0.000000,0.000000,9.810000,9.850000,9.890000,14.180000,15.560000,15.690000,0.000000,0.000000
25%,0.280000,0.290000,11.200000,11.300000,0.000000,0.000000,16.970000,17.020000,17.100000,55.770000,56.520000,57.270000,0.000000,0.000000
50%,0.540000,0.550000,13.800000,13.900000,0.000000,0.000000,19.430000,19.500000,19.580000,73.460000,73.830000,74.250000,0.200000,0.400000
75%,1.220000,1.240000,16.800000,16.800000,0.000000,250.000000,24.150000,24.300000,24.450000,84.200000,84.500000,84.810000,0.800000,0.900000
max,4.720000,4.790000,20.000000,21.000000,7.800000,963.000000,35.450000,35.470000,35.690000,96.480000,96.480000,96.480000,3.100000,3.800000

In [6]:
# Verificando dados faltantes por coluna
dfFT.isna().sum()

data                 0
painel           14019
energia_dia      14496
energia_ano      14496
energia_total    14496
potencia         14496
power_led            0
solarnet_led         0
solarweb_led         0
dtype: int64

Observado que cinco colunas (painel, energia_dia, energia_ano, energia_total, potencia) possuiam dados faltantes por falta/erro de medição, com isso optou-se por remover essas linhas com registros faltantes, alguns casos até foi registrado qual foi o painel mas sem registro de outras informações, sendo assim, dados irrelevantes.

In [7]:
dfFT.dropna(inplace=True)
dfFT.isna().sum()

data             0
painel           0
energia_dia      0
energia_ano      0
energia_total    0
potencia         0
power_led        0
solarnet_led     0
solarweb_led     0
dtype: int64

In [8]:
dfFT.isin({0}).sum()

data                  0
painel                0
energia_dia      174617
energia_ano           0
energia_total         0
potencia         350949
power_led           302
solarnet_led        302
solarweb_led        302
dtype: int64

In [9]:
Valores com zero são aceitváveis pois em determinados períodos do dia não ocorrem radiação solar sobre os paineis.

SyntaxError: invalid syntax (<ipython-input-9-46271e8d5e33>, line 1)

In [ ]:
verificação da existencia valores negativos
Perguntar o que é as colunas power_led, leds

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4297 entries, 0 to 4296
Data columns (total 15 columns):
data                       4297 non-null object
deficit_vapor_vmin         4297 non-null float64
deficit_vapor_vmedio       4297 non-null float64
ponto_orvalho_vmin         4297 non-null float64
ponto_orvalho_vmedio       4297 non-null float64
precipitacao_valor         4297 non-null float64
radiacao_solar_valor       4297 non-null float64
temperatura_ar_vmin        4297 non-null float64
temperatura_ar_vmedio      4297 non-null float64
temperatura_ar_vmax        4297 non-null float64
umidade_ar_vmin            4297 non-null float64
umidade_ar_vmedio          4297 non-null float64
umidade_ar_vmax            4297 non-null float64
velocidade_vento_vmedio    4297 non-null float64
velocidade_vento_vmax      4297 non-null float64
dtypes: float64(14), object(1)
memory usage: 503.6+ KB

In [11]:
dfMT.isna().sum()

data                       0
deficit_vapor_vmin         0
deficit_vapor_vmedio       0
ponto_orvalho_vmin         0
ponto_orvalho_vmedio       0
precipitacao_valor         0
radiacao_solar_valor       0
temperatura_ar_vmin        0
temperatura_ar_vmedio      0
temperatura_ar_vmax        0
umidade_ar_vmin            0
umidade_ar_vmedio          0
umidade_ar_vmax            0
velocidade_vento_vmedio    0
velocidade_vento_vmax      0
dtype: int64

In [12]:
dfMT.isnull().sum()

data                       0
deficit_vapor_vmin         0
deficit_vapor_vmedio       0
ponto_orvalho_vmin         0
ponto_orvalho_vmedio       0
precipitacao_valor         0
radiacao_solar_valor       0
temperatura_ar_vmin        0
temperatura_ar_vmedio      0
temperatura_ar_vmax        0
umidade_ar_vmin            0
umidade_ar_vmedio          0
umidade_ar_vmax            0
velocidade_vento_vmedio    0
velocidade_vento_vmax      0
dtype: int64

In [13]:
Dados com valores zero
Existem colunas com valores zero, porém, é aceitável visto que são medidas momentánes podendo ser variáveis.

SyntaxError: invalid syntax (<ipython-input-13-63c015b2a255>, line 1)

In [14]:
# Dados faltantes por coluna
dfMT.isin({0}).sum()

data                          0
deficit_vapor_vmin            0
deficit_vapor_vmedio          0
ponto_orvalho_vmin            0
ponto_orvalho_vmedio          0
precipitacao_valor         4147
radiacao_solar_valor       2405
temperatura_ar_vmin           0
temperatura_ar_vmedio         0
temperatura_ar_vmax           0
umidade_ar_vmin               0
umidade_ar_vmedio             0
umidade_ar_vmax               0
velocidade_vento_vmedio    1610
velocidade_vento_vmax      1409
dtype: int64

In [15]:
verificar existencia de valores negativos
criar colunas de hora e deixar a de data apenas para data

SyntaxError: invalid syntax (<ipython-input-15-85dd1cf49a71>, line 1)

In [16]:
dfMT.head()

,data,deficit_vapor_vmin,deficit_vapor_vmedio,ponto_orvalho_vmin,ponto_orvalho_vmedio,precipitacao_valor,radiacao_solar_valor,temperatura_ar_vmin,temperatura_ar_vmedio,temperatura_ar_vmax,umidade_ar_vmin,umidade_ar_vmedio,umidade_ar_vmax,velocidade_vento_vmedio,velocidade_vento_vmax
0,2018-09-30 23:50:06.000,0.25,0.25,18.9,18.9,0.0,0.0,20.79,20.80,20.82,89.38,89.56,89.74,0.0,0.0
1,2018-09-30 23:40:07.000,0.26,0.26,19.0,19.0,0.0,0.0,20.87,20.93,21.00,88.80,88.94,89.08,0.2,0.5
2,2018-09-30 23:30:06.000,0.27,0.27,19.0,19.0,0.0,0.0,20.98,21.00,21.02,88.95,88.99,89.03,0.0,0.1
3,2018-09-30 23:20:07.000,0.27,0.27,19.1,19.1,0.0,0.0,21.06,21.06,21.07,88.88,89.00,89.13,0.0,0.1
4,2018-09-30 23:10:06.000,0.25,0.25,19.1,19.1,0.0,0.0,20.91,20.94,20.97,89.47,89.66,89.85,0.0,0.0

In [19]:
dfMT['dia'] = pd.to_datetime(dfMT['data']).dt.date
dfMT['hora'] = pd.to_datetime(dfMT['data']).dt.hour

In [20]:
dfMT.head()

,data,deficit_vapor_vmin,deficit_vapor_vmedio,ponto_orvalho_vmin,ponto_orvalho_vmedio,precipitacao_valor,radiacao_solar_valor,temperatura_ar_vmin,temperatura_ar_vmedio,temperatura_ar_vmax,umidade_ar_vmin,umidade_ar_vmedio,umidade_ar_vmax,velocidade_vento_vmedio,velocidade_vento_vmax,dia,hora
0,2018-09-30 23:50:06.000,0.25,0.25,18.9,18.9,0.0,0.0,20.79,20.80,20.82,89.38,89.56,89.74,0.0,0.0,2018-09-30,23
1,2018-09-30 23:40:07.000,0.26,0.26,19.0,19.0,0.0,0.0,20.87,20.93,21.00,88.80,88.94,89.08,0.2,0.5,2018-09-30,23
2,2018-09-30 23:30:06.000,0.27,0.27,19.0,19.0,0.0,0.0,20.98,21.00,21.02,88.95,88.99,89.03,0.0,0.1,2018-09-30,23
3,2018-09-30 23:20:07.000,0.27,0.27,19.1,19.1,0.0,0.0,21.06,21.06,21.07,88.88,89.00,89.13,0.0,0.1,2018-09-30,23
4,2018-09-30 23:10:06.000,0.25,0.25,19.1,19.1,0.0,0.0,20.91,20.94,20.97,89.47,89.66,89.85,0.0,0.0,2018-09-30,23

In [21]:
temp = pd.DataFrame(dfMT.groupby('dia').temperatura_ar_vmedio.mean()).reset_index()
temp

           dia  temperatura_ar_vmedio
0   2018-09-01              23.413986
1   2018-09-02              23.829161
2   2018-09-03              18.007552
3   2018-09-04              13.846643
4   2018-09-05              14.679510
5   2018-09-06              16.898889
6   2018-09-07              19.353986
7   2018-09-08              20.933007
8   2018-09-09              18.788671
9   2018-09-10              19.592867
10  2018-09-11              18.940486
11  2018-09-12              19.674085
12  2018-09-13              21.570769
13  2018-09-14              17.696667
14  2018-09-15              19.066736
15  2018-09-16              18.678252
16  2018-09-17              17.327500
17  2018-09-18              21.129790
18  2018-09-19              23.411458
19  2018-09-20              19.924965
20  2018-09-21              21.719720
21  2018-09-22              23.137222
22  2018-09-23              23.598322
23  2018-09-24              24.318392
24  2018-09-25              22.807483
25  2018-09-26              24.222986
26  2018-09-27              21.764965
27  2018-09-28              21.818531
28  2018-09-29              24.209720
29  2018-09-30              23.595734

In [22]:
trace1 = go.Scatter(
                    x = temp['dia'],
                    y = temp['temperatura_ar_vmedio'],
                    mode = 'lines+markers')


data = [trace1]
layout = dict(title = 'Quantidade de veículos por ano',
              xaxis= dict(title= 'Data',zeroline= False,
                         ticks='outside'),
              yaxis = dict(title= 'Total de veículos',
                            ticks='outside'
                          )
             )
fig = dict(data = data, layout = layout)
iplot(fig)

In [ ]:
tomar cuidado com o campo energi_dia , pois tem delay, pegar valor de ultimo valor de 23:59:xx hs

2 – Liste as principais dúvidas sobre os dados (pelo menos 5). Seja específico e faça perguntas que possam te ajudar a escolher quais campos serão úteis e podem te ajudar a ter ideias de como montar sua solução no futuro. Também faça perguntas que te ajudem a identificar campos irrelevantes e que devem ser descartadas no futuro. Questões simples como “Qual a média/variância/desvio padrão do campo X?” não serão aceitas, mas perceba que pode ser interessante realizar esses cálculos para ter respostas de questões mais elaboradas. Você também pode elaborar uma questão como essa, desde faça esses cálculos para todos os campos, por exemplo: “Qual é a média, variância e desvio padrão de cada campo numérico do dataset?”  (2 pontos).

In [ ]:
campos descartados
5 perguntas

3 – Plote gráficos para responder às questões levantadas acima. Escolha os gráficos mais adequados para cada questão. Seja convincente e didático: pense que o observador pode não entender sobre o problema, como convencê-lo das suas afirmações? Capriche na apresentação! Faça uso de cores, legendas e outros recursos que deixem os gráficos visualmente agradáveis. (3 pontos)

In [ ]:
gráfico para cada pergunta

4 – Para cada uma das questões que você elaborou no exercício 2, escreva uma breve conclusão após as observações feitas no exercício 3. Seja realista, tome suas conclusões com base nos dados e tome cuidado para não fazer afirmações difíceis de serem suportadas pelas suas análises (2 pontos).