# Especialização em Ciência de Dados - Turma 2018.1 - Facens
## TRABALHO DE CONCLUSÃO DE CURSO


|**Professor:**|Fernando Vieira da Silva, M.Sc.|
|-----|-----------------------------------|

|**Nome:**|José Diniz Junior            |**RA:**|183134|
|-----|-----------------------------|---|------|
|**Nome:**|Roberto Leonardo Rodrigues   |**RA:**|060235|

In [ ]:
'''Exemplos de predição de radiação
https://www.kaggle.com/dronio/SolarEnergy/kernels
LSTM model = https://www.kaggle.com/lukashenry/radiation-time-serie-predictions
random forest = https://www.kaggle.com/ssudeep/solar-radiation-prediction-using-random-forest
https://www.kaggle.com/callumdownie/hi-seas-solar-irradiance-prediction

https://www.kaggle.com/wglacier/solar-radiation-predict
https://machinelearningmastery.com/time-series-prediction-lstm-recurrent-neural-networks-python-keras/

https://github.com/ColasGael/Machine-Learning-for-Solar-Energy-Prediction/blob/master/Recurrent%20Neural%20Network/rnn.py
'''

In [1]:
import pandas as pd

In [2]:
mt = pd.read_csv('Meteorologico.csv')
mt.head()

,data,deficit_vapor_vmin,deficit_vapor_vmedio,ponto_orvalho_vmin,ponto_orvalho_vmedio,precipitacao_valor,radiacao_solar_valor,temperatura_ar_vmin,temperatura_ar_vmedio,temperatura_ar_vmax,umidade_ar_vmin,umidade_ar_vmedio,umidade_ar_vmax,velocidade_vento_vmedio,velocidade_vento_vmax
0,2018-09-30 23:50:06.000,0.25,0.25,18.9,18.9,0.0,0.0,20.79,20.80,20.82,89.38,89.56,89.74,0.0,0.0
1,2018-09-30 23:40:07.000,0.26,0.26,19.0,19.0,0.0,0.0,20.87,20.93,21.00,88.80,88.94,89.08,0.2,0.5
2,2018-09-30 23:30:06.000,0.27,0.27,19.0,19.0,0.0,0.0,20.98,21.00,21.02,88.95,88.99,89.03,0.0,0.1
3,2018-09-30 23:20:07.000,0.27,0.27,19.1,19.1,0.0,0.0,21.06,21.06,21.07,88.88,89.00,89.13,0.0,0.1
4,2018-09-30 23:10:06.000,0.25,0.25,19.1,19.1,0.0,0.0,20.91,20.94,20.97,89.47,89.66,89.85,0.0,0.0

In [3]:
mt.isna().sum()

data                       0
deficit_vapor_vmin         0
deficit_vapor_vmedio       0
ponto_orvalho_vmin         0
ponto_orvalho_vmedio       0
precipitacao_valor         0
radiacao_solar_valor       0
temperatura_ar_vmin        0
temperatura_ar_vmedio      0
temperatura_ar_vmax        0
umidade_ar_vmin            0
umidade_ar_vmedio          0
umidade_ar_vmax            0
velocidade_vento_vmedio    0
velocidade_vento_vmax      0
dtype: int64

In [4]:
mt.describe()

,deficit_vapor_vmin,deficit_vapor_vmedio,ponto_orvalho_vmin,ponto_orvalho_vmedio,precipitacao_valor,radiacao_solar_valor,temperatura_ar_vmin,temperatura_ar_vmedio,temperatura_ar_vmax,umidade_ar_vmin,umidade_ar_vmedio,umidade_ar_vmax,velocidade_vento_vmedio,velocidade_vento_vmax
count,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000,4297.000000
mean,0.897098,0.912234,13.781941,13.871841,0.021131,160.484524,20.504631,20.597866,20.695986,68.827389,69.273230,69.724329,0.461089,0.554689
std,0.873278,0.887208,3.273901,3.245847,0.183947,253.018622,5.225928,5.262248,5.300486,19.414074,19.229212,19.057480,0.558024,0.614450
min,0.050000,0.050000,2.900000,3.400000,0.000000,0.000000,9.810000,9.850000,9.890000,14.180000,15.560000,15.690000,0.000000,0.000000
25%,0.280000,0.290000,11.200000,11.300000,0.000000,0.000000,16.970000,17.020000,17.100000,55.770000,56.520000,57.270000,0.000000,0.000000
50%,0.540000,0.550000,13.800000,13.900000,0.000000,0.000000,19.430000,19.500000,19.580000,73.460000,73.830000,74.250000,0.200000,0.400000
75%,1.220000,1.240000,16.800000,16.800000,0.000000,250.000000,24.150000,24.300000,24.450000,84.200000,84.500000,84.810000,0.800000,0.900000
max,4.720000,4.790000,20.000000,21.000000,7.800000,963.000000,35.450000,35.470000,35.690000,96.480000,96.480000,96.480000,3.100000,3.800000

In [10]:
import numpy as np
histogram_intersection = lambda a, b: np.minimum(a, b).sum().round(decimals=1)

In [11]:
histogram_intersection

In [32]:
mt.corr(method='pearson')

KeyError: <function <lambda> at 0x00000243A98F0A60>

In [28]:
mt[['radiacao_solar_valor','precipitacao_valor']].corr(method='kendall')

                      radiacao_solar_valor  precipitacao_valor
radiacao_solar_valor              1.000000           -0.053679
precipitacao_valor               -0.053679            1.000000