# Material de aula - FACENS - Aprendizado de Máquina


## Scikit Learn - Laboratório 01

In [1]:
#CÉLULA SCIKIT-LIB-01
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
#CÉLULA SCIKIT-LIB-02
def tales(x1, x1_min, x1_max, x2_min, x2_max) :
    '''
    Esta função faz o escalamento de 1 amostra x1, que pertence ao intervalo [x1_min, x1_max], 
    dentro do intervalo [x2_min, x2_max]
    
    Parametros
    -----------
    x1     -> valor a ser normalizado
    x1_min -> valor minimo atingido por x1
    x1_max -> valor maximo atingido por x1
    x2_min -> valor minimo da escala de destino
    x2_max -> valor maximo da escala de destino    
    
    Retorno
    -----------  
    valor de x1, que pertence ao intervalo [x1_min, x1_max], projetado dentro do intervalo [x2_min, x2_max]
    '''
   
    #Teorema de Tales
    # ( x2 - x2_min ) / ( x2_max - x2_min ) = ( x1 - x1_min ) / (x1_max - % x1_min);
    
    #Definindo x1 como a escala do vetor dado e x2 como a escala de saída (variavel de interesse), isola-se x2:
    x2 = ( ( x1 - x1_min ) / (x1_max - x1_min) )* ( x2_max - x2_min ) + x2_min
    
    return x2

In [3]:
#CÉLULA SCIKIT-LIB-03
def scale(x2_min, x2_max, sampleArray) :
    '''
    Esta função faz o escalamento de 1 vetor de amostras para dentro do intervalo [x2_min, x2_max]
    Ela retorna um vetor com os dados normalizados dentro do dominio dado
    
    Parametros
    -----------
    x2_min      -> valor minimo da escala de destino
    x2_max      -> valor maximo da escala de destino
    sampleArray -> vetor a ser normalizado   
    
    Retorno
    -----------  
    vetor sampleArray projetado dentro do intervalo [x2_min, x2_max]   
    '''    
    x_max = max(sampleArray)
    x_min = min(sampleArray)
    
    sampleArrayNorm = [tales(x, x_min, x_max, x2_min, x2_max) for x in sampleArray]
    
    return sampleArrayNorm

## Será utilizado o mesmo dataset de treinamento do PERCEPTRON

In [4]:
#Carregando dataset de treino
dfDataFile = pd.read_csv('Lab01_training.csv',sep=';',decimal=',',thousands='.')
dfDataFile.head()

   Amostra      x1      x2       x3  d
0        1 -0.6508  0.1097   4.0009 -1
1        2 -1.4492  0.8896   4.4005 -1
2        3  2.0850  0.6876  12.0710 -1
3        4  0.2626  1.1476   7.7985  1
4        5  0.6418  1.0234   7.0427  1

In [5]:
#Normalizando dados de treino
dfNormData = dfDataFile.copy()
dfNormData['x1'] = scale(-1,1,dfNormData['x1'])
dfNormData['x2'] = scale(-1,1,dfNormData['x2'])
dfNormData['x3'] = scale(-1,1,dfNormData['x3'])
dfNormData

    Amostra        x1        x2        x3  d
0         1 -0.590291 -0.543460 -0.560073 -1
1         2 -1.000000  0.616328 -0.482824 -1
2         3  0.813619  0.315934  1.000000 -1
3         4 -0.121568  1.000000  0.174061  1
4         5  0.073023  0.815302  0.027953  1
5         6 -0.124493  0.294223  0.276131 -1
6         7  0.316108  0.192059  0.105647  1
7         8 -0.209422 -0.201130  0.032786 -1
8         9 -0.250115  0.075024 -0.438149  1
9        10 -0.278339 -0.013607 -0.283361  1
10       11 -0.033612  0.315042  0.257225 -1
11       12 -0.115975  0.823184  0.057086  1
12       13 -0.008005  0.014797  0.113457 -1
13       14 -0.046493 -0.895011 -0.269907 -1
14       15  0.482168 -0.466577  0.325968 -1
15       16 -0.724072 -1.000000 -0.908949 -1
16       17 -0.068815  0.851141  0.113611  1
17       18 -0.146303  0.410960  0.052543  1
18       19 -0.153025  0.782586 -0.067506  1
19       20  0.076359 -0.381961 -0.193122  1
20       21 -0.315184 -0.373188  0.066771 -1
21       22 -0.665315  0.601309 -0.584179  1
22       23 -0.801560  0.240092 -0.855884  1
23       24  0.016011 -0.515503 -0.233873  1
24       25 -0.882383  0.449922 -1.000000  1
25       26 -0.053266 -0.546583 -0.238899 -1
26       27 -0.308308  0.184029  0.054728 -1
27       28  1.000000  0.699457  0.833459  1
28       29  0.777647  0.214217  0.778712 -1
29       30 -0.153076 -0.318314 -0.277407  1

## 1 - Utilizando o MinMax Scaler faça a normalização do mesmo dataset e compare o resultado

## 1.1 - importe o pacote MinMaxScaler da biblioteca sklearn.preprocessing

In [6]:
from sklearn.preprocessing import MinMaxScaler

## 1.2 - Crie um dataset auxiliar com as colunas de treinamento x1, x2, x3

In [7]:
dfAux = dfDataFile[['x1','x2','x3']]
dfAux

        x1      x2       x3
0  -0.6508  0.1097   4.0009
1  -1.4492  0.8896   4.4005
2   2.0850  0.6876  12.0710
3   0.2626  1.1476   7.7985
4   0.6418  1.0234   7.0427
5   0.2569  0.6730   8.3265
6   1.1155  0.6043   7.4446
7   0.0914  0.3399   7.0677
8   0.0121  0.5256   4.6316
9  -0.0429  0.4660   5.4323
10  0.4340  0.6870   8.2287
11  0.2735  1.0287   7.1934
12  0.4839  0.4851   7.4850
13  0.4089 -0.1267   5.5019
14  1.4391  0.1614   8.5843
15 -0.9115 -0.1973   2.1962
16  0.3654  1.0475   7.4858
17  0.2144  0.7515   7.1699
18  0.2013  1.0014   6.5489
19  0.6483  0.2183   5.8991
20 -0.1147  0.2242   7.2435
21 -0.7970  0.8795   3.8762
22 -1.0625  0.6366   2.4707
23  0.5307  0.1285   5.6883
24 -1.2200  0.7777   1.7252
25  0.3957  0.1076   5.6623
26 -0.1013  0.5989   7.1812
27  2.4482  0.9455  11.2095
28  2.0149  0.6192  10.9263
29  0.2012  0.2611   5.4631

## 1.3 Aplique a normalização MinMax

In [8]:
type(dfAux.values)

numpy.ndarray

In [9]:
scaler = MinMaxScaler(feature_range=(-1,1))

In [10]:
scalerresult = scaler.fit(dfAux.values)
scalerresult

MinMaxScaler(copy=True, feature_range=(-1, 1))

## 1.4 Use a função transform para converter o resultado em um dataframe

In [11]:
NormDataArray = scalerresult.transform(dfAux)
NormDataArray

array([[-0.59029096, -0.54346048, -0.56007269],
       [-1.        ,  0.61632835, -0.48282395],
       [ 0.81361934,  0.31593427,  1.        ],
       [-0.12156822,  1.        ,  0.17406097],
       [ 0.07302304,  0.81530225,  0.02795337],
       [-0.12449325,  0.29422262,  0.27613138],
       [ 0.31610817,  0.19205889,  0.10564674],
       [-0.20942167, -0.2011302 ,  0.03278625],
       [-0.25011546,  0.07502417, -0.43814881],
       [-0.27833941, -0.01360696, -0.28336136],
       [-0.03361215,  0.31504201,  0.25722515],
       [-0.11597475,  0.82318388,  0.05708597],
       [-0.00800534,  0.01479664,  0.11345667],
       [-0.04649253, -0.89501078, -0.26990663],
       [ 0.4821676 , -0.46657744,  0.32596803],
       [-0.72407246, -1.        , -0.90894856],
       [-0.06881511,  0.85114135,  0.11361132],
       [-0.14630266,  0.41095992,  0.05254306],
       [-0.15302509,  0.78258607, -0.06750565],
       [ 0.0763586 , -0.38196148, -0.19312185],
       [-0.31518448, -0.3731876 ,  0.06677106],
       [-0.66531534,  0.60130865, -0.58417909],
       [-0.80156001,  0.2400922 , -0.85588355],
       [ 0.01601067, -0.51550301, -0.23387268],
       [-0.88238313,  0.44992193, -1.        ],
       [-0.05326628, -0.54658339, -0.23889888],
       [-0.3083081 ,  0.18402855,  0.05472752],
       [ 1.        ,  0.69945721,  0.83345899],
       [ 0.77764664,  0.21421667,  0.77871213],
       [-0.15307641, -0.31831363, -0.27740726]])