# Material de aula - FACENS - Aprendizado de Máquina

# <center> RESOLUÇÃO DA ATIVIDADE </center>


## ADALINE e Regra Delta - Laboratório 01

In [1]:
#CÉLULA ADALINE-LIB-01
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
#from enum import Enum
#from operator import xor
%matplotlib inline

# 1 - Criando a função leitura dos dados do problema

Utilizando Jupyter e NumPy: para o problema apresentado construa uma função que carrega os dados de um arquivo separado por vírgulas (csv)
Assinatura: **def loadDataFile(filename) :**
        
**Retorno da Função:** um dataframe do pandas contendo os dados lidos do arquivo

**NOTA**: Verifique o separador utilizado no arquivo para a correta validação dos dados.

In [2]:
#CÉLULA ADALINE-LIB-02

#Função para carregamento de dados de treinamento

def loadDataFile(filename) :
    '''
    Esta função faz o carregamento de dados de um arquivo separado por virgulas (csv)
    
    Parametros
    -----------
    filename -> nome do arquivo de dados em formato csv
    
    
    Retorno
    -----------  
    dataframe contendo os dados do arquivo formatados numericamente.
    '''

    #Carga do arquivo
    dfFile = pd.read_csv(filename, sep=';', decimal=',', thousands='.')    
    return dfFile

In [3]:
#Teste
dfTrainingFile = loadDataFile('Lab01_training.csv')
print(dfTrainingFile.dtypes)

Amostra      int64
x1         float64
x2         float64
x3         float64
x4         float64
d            int64
dtype: object

In [4]:
dfTrainingFile.head()

   Amostra      x1      x2      x3      x4  d
0        1  0.4329 -1.3719  0.7022 -0.8535  1
1        2  0.3024  0.2286  0.8630  2.7909 -1
2        3  0.1349 -0.6445  1.0530  0.5687 -1
3        4  0.3374 -1.7163  0.3670 -0.6283 -1
4        5  1.1434 -0.0485  0.6637  1.2606  1

In [5]:
dfTestFile = loadDataFile('Lab01_operation.csv')
print(dfTestFile.dtypes)

Amostra      int64
x1         float64
x2         float64
x3         float64
x4         float64
dtype: object

In [6]:
dfTestFile.head()

   Amostra      x1      x2      x3      x4
0        1  0.9694  0.6909  0.4334  3.4965
1        2  0.5427  1.3832  0.6390  4.0352
2        3  0.6081 -0.9196  0.5925  0.1016
3        4 -0.1618  0.4694  0.2030  3.0117
4        5  0.1870 -0.2578  0.6124  1.7749

## Validação
``
dfTrainingFile = loadDataFile('Lab01_training.csv')
print(dfTrainingFile.dtypes)
``

**Valor esperado:**

    Amostra      int64
    x1         float64
    x2         float64
    x3         float64
    x4         float64
    d            int64
    dtype: object

``
dfTrainingFiles.head()
``

**Valor esperado:**

    Amostra	x1	x2	x3	x4	d
    0	1	0.4329	-1.3719	0.7022	-0.8535	1
    1	2	0.3024	0.2286	0.8630	2.7909	-1
    2	3	0.1349	-0.6445	1.0530	0.5687	-1
    3	4	0.3374	-1.7163	0.3670	-0.6283	-1
    4	5	1.1434	-0.0485	0.6637	1.2606	1

dfTestFile = loadDataFile('Lab01_operation.csv')
print(dfTestFile.dtypes)
``

**Valor esperado:**

    Amostra      int64
    x1         float64
    x2         float64
    x3         float64
    x4         float64
    dtype: object

``
dfTestFile.head()
``

**Valor esperado:**

    Amostra	x1	x2	x3	x4
    0	1	0.9694	0.6909	0.4334	3.4965
    1	2	0.5427	1.3832	0.6390	4.0352
    2	3	0.6081	-0.9196	0.5925	0.1016
    3	4	-0.1618	0.4694	0.2030	3.0117
    4	5	0.1870	-0.2578	0.6124	1.7749