# Material de aula - FACENS - Aprendizado de Máquina

# <center> RESOLUÇÃO DA ATIVIDADE </center>


## Perceptron e Regra de Aprendizado de Hebb - Laboratório 02

In [1]:
#CÉLULA PERCEPTRON-LIB-01
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
#CÉLULA PERCEPTRON-LIB-02
#Função para carregamento de dados de treinamento
def loadDataFile(filename) :
    '''
    Esta função faz o carregamento de dados de um arquivo separado por virgulas (csv)
    
    Parametros
    -----------
    filename -> nome do arquivo de dados em formato csv
    
    
    Retorno
    -----------  
    dataframe contendo os dados do arquivo formatados numericamente.
    '''    
    dfFile = pd.read_csv(filename, sep=';', decimal=',', thousands='.')
    
    return dfFile

# 1 - Criando a função de escala - Parte 1

Utilizando Jupyter e NumPy: para a função de variável contínua apresentada, construa uma função para o cálculo da escala dos dados para o domínio da função de ativação.

Assinatura: **def tales(x1, x1_min, x1_max, x2_min, x2_max) :**

### esta função faz o escalamento de 1 amostra x1, que pertence ao intervalo [x1_min, x1_max],
### dentro do intervalo [x2_min, x2_max]
    
**Retorno da Função:** valor dentro do domínio dado

In [3]:
#CÉLULA PERCEPTRON-LIB-03
# Função para cálculo de normalização de uma amostra
def tales(x1, x1_min, x1_max, x2_min, x2_max) :
    '''
    Esta função faz o escalamento de 1 amostra x1, que pertence ao intervalo [x1_min, x1_max], 
    dentro do intervalo [x2_min, x2_max]
    
    Parametros
    -----------
    x1     -> valor a ser normalizado
    x1_min -> valor minimo atingido por x1
    x1_max -> valor maximo atingido por x1
    x2_min -> valor minimo da escala de destino
    x2_max -> valor maximo da escala de destino    
    
    Retorno
    -----------  
    valor de x1, que pertence ao intervalo [x1_min, x1_max], projetado dentro do intervalo [x2_min, x2_max]
    '''
    
    #RESOLUÇÃO - INICIO

    #Teorema de Tales
    # ( x2 - x2_min ) / ( x2_max - x2_min ) = ( x1 - x1_min ) / (x1_max - % x1_min);
    
    #Definindo x1 como a escala do vetor dado e x2 como a escala de saída (variavel de interesse), isola-se x2:
    x2 = ( ( x1 - x1_min ) / (x1_max - x1_min) )* ( x2_max - x2_min ) + x2_min

    #RESOLUÇÃO - FIM

    return x2

In [4]:
#Teste
print(tales(5, -10, 10, -1, 1)) #Valor esperado: 0.5

print(tales(-5, -10, 10, -1, 1)) #Valor esperado: -0.5

print(tales(-10, -10, 10, -1, 1)) #Valor esperado: -1.0

print(tales(10, -10, 10, -1, 1)) #Valor esperado: 1.0

0.5
-0.5
-1.0
1.0

## Validação
print(tales(5, -10, 10, -1, 1)) #Valor esperado: 0.5

print(tales(-5, -10, 10, -1, 1)) #Valor esperado: -0.5

print(tales(-10, -10, 10, -1, 1)) #Valor esperado: -1.0

print(tales(10, -10, 10, -1, 1)) #Valor esperado: 1.0

# 2 - Criando a função de escala - Parte 2

Utilizando Jupyter e NumPy: Utilizando Jupyter e NumPy: para a função de variável contínua apresentada, construa uma função para o cálculo da escala do vetor de dados para o domínio da função de ativação.

Assinatura: **def scale(x2_min, x2_max, sampleArray) :**

### esta função faz o escalamento de 1 array de dados que para dentro do intervalo [x2_min, x2_max]
    
**Retorno da Função:** valor dentro do domínio dado

**NOTA**: Não sabemos os limites da escala do array, temos que descobrir!

In [5]:
#CÉLULA PERCEPTRON-LIB-04
def scale(x2_min, x2_max, sampleArray) :    
    '''
    Esta função faz o escalamento de 1 vetor de amostras para dentro do intervalo [x2_min, x2_max]
    Ela retorna um vetor com os dados normalizados dentro do dominio dado
    
    Parametros
    -----------
    x2_min      -> valor minimo da escala de destino
    x2_max      -> valor maximo da escala de destino
    sampleArray -> vetor a ser normalizado   
    
    Retorno
    -----------  
    vetor sampleArray projetado dentro do intervalo [x2_min, x2_max]   
    '''
    
    #RESOLUÇÃO - INICIO
    x_max = max(sampleArray)
    x_min = min(sampleArray)
    
    sampleArrayNorm = [tales(x, x_min, x_max, x2_min, x2_max) for x in sampleArray]
    #RESOLUÇÃO - FIM
    
    return sampleArrayNorm

In [6]:
#Teste
v = np.array([5, -5, 10, -10, 0, 3, -3, 4, -4, 7])
scale(-1, 1, v)

[0.5,
 -0.5,
 1.0,
 -1.0,
 0.0,
 0.30000000000000004,
 -0.30000000000000004,
 0.3999999999999999,
 -0.4,
 0.7]

## Validação
``
v = np.array([5, -5, 10, -10, 0, 3, -3, 4, -4, 7])
scale(-1, 1, v)
``

**Valor esperado:**
    [0.5, -0.5, 1.0, -1.0, 0.0, 0.3, -0.3, 0.39, -0.4, 0.7]

# 3 - Teste sua função de escala com os dados do problema

Faça a carga dos dados e verifique se consegue fazer o escalamento das colunas de dados de treinamento e operação

In [7]:
#Carregando dataset de treino
dfTrainingFile = loadDataFile('Lab01_training.csv')
dfTrainingFile

    Amostra      x1      x2       x3  d
0         1 -0.6508  0.1097   4.0009 -1
1         2 -1.4492  0.8896   4.4005 -1
2         3  2.0850  0.6876  12.0710 -1
3         4  0.2626  1.1476   7.7985  1
4         5  0.6418  1.0234   7.0427  1
5         6  0.2569  0.6730   8.3265 -1
6         7  1.1155  0.6043   7.4446  1
7         8  0.0914  0.3399   7.0677 -1
8         9  0.0121  0.5256   4.6316  1
9        10 -0.0429  0.4660   5.4323  1
10       11  0.4340  0.6870   8.2287 -1
11       12  0.2735  1.0287   7.1934  1
12       13  0.4839  0.4851   7.4850 -1
13       14  0.4089 -0.1267   5.5019 -1
14       15  1.4391  0.1614   8.5843 -1
15       16 -0.9115 -0.1973   2.1962 -1
16       17  0.3654  1.0475   7.4858  1
17       18  0.2144  0.7515   7.1699  1
18       19  0.2013  1.0014   6.5489  1
19       20  0.6483  0.2183   5.8991  1
20       21 -0.1147  0.2242   7.2435 -1
21       22 -0.7970  0.8795   3.8762  1
22       23 -1.0625  0.6366   2.4707  1
23       24  0.5307  0.1285   5.6883  1
24       25 -1.2200  0.7777   1.7252  1
25       26  0.3957  0.1076   5.6623 -1
26       27 -0.1013  0.5989   7.1812 -1
27       28  2.4482  0.9455  11.2095  1
28       29  2.0149  0.6192  10.9263 -1
29       30  0.2012  0.2611   5.4631  1

In [8]:
#Normalizando dados de treino
dfTrainingFileNorm = dfTrainingFile.copy()
dfTrainingFileNorm['x1'] = scale(-1,1, dfTrainingFile['x1'])
dfTrainingFileNorm['x2'] = scale(-1,1, dfTrainingFile['x2'])
dfTrainingFileNorm['x3'] = scale(-1,1, dfTrainingFile['x3'])

dfTrainingFileNorm

    Amostra        x1        x2        x3  d
0         1 -0.590291 -0.543460 -0.560073 -1
1         2 -1.000000  0.616328 -0.482824 -1
2         3  0.813619  0.315934  1.000000 -1
3         4 -0.121568  1.000000  0.174061  1
4         5  0.073023  0.815302  0.027953  1
5         6 -0.124493  0.294223  0.276131 -1
6         7  0.316108  0.192059  0.105647  1
7         8 -0.209422 -0.201130  0.032786 -1
8         9 -0.250115  0.075024 -0.438149  1
9        10 -0.278339 -0.013607 -0.283361  1
10       11 -0.033612  0.315042  0.257225 -1
11       12 -0.115975  0.823184  0.057086  1
12       13 -0.008005  0.014797  0.113457 -1
13       14 -0.046493 -0.895011 -0.269907 -1
14       15  0.482168 -0.466577  0.325968 -1
15       16 -0.724072 -1.000000 -0.908949 -1
16       17 -0.068815  0.851141  0.113611  1
17       18 -0.146303  0.410960  0.052543  1
18       19 -0.153025  0.782586 -0.067506  1
19       20  0.076359 -0.381961 -0.193122  1
20       21 -0.315184 -0.373188  0.066771 -1
21       22 -0.665315  0.601309 -0.584179  1
22       23 -0.801560  0.240092 -0.855884  1
23       24  0.016011 -0.515503 -0.233873  1
24       25 -0.882383  0.449922 -1.000000  1
25       26 -0.053266 -0.546583 -0.238899 -1
26       27 -0.308308  0.184029  0.054728 -1
27       28  1.000000  0.699457  0.833459  1
28       29  0.777647  0.214217  0.778712 -1
29       30 -0.153076 -0.318314 -0.277407  1

In [9]:
#Carregando dataset de teste
dfTestFile = loadDataFile('Lab01_operation.csv')
dfTestFile

       x1      x2      x3
0 -0.3565  0.0620  5.9891
1 -0.7842  1.1267  5.5912
2  0.3012  0.5611  5.8234
3  0.7757  1.0648  8.0677
4  0.1570  0.8028  6.3040
5 -0.7014  1.0316  3.6005
6  0.3748  0.1536  6.1537
7 -0.6920  0.9404  4.4058
8 -1.3970  0.7141  4.9263
9 -1.8842 -0.2805  1.2548

In [10]:
#Normalizando dados de teste
dfTestFileNorm = dfTestFile.copy()
dfTestFileNorm['x1'] = scale(-1,1, dfTestFileNorm['x1'])
dfTestFileNorm['x2'] = scale(-1,1, dfTestFileNorm['x2'])
dfTestFileNorm['x3'] = scale(-1,1, dfTestFileNorm['x3'])

dfTestFileNorm

         x1        x2        x3
0  0.148690 -0.513218  0.389805
1 -0.172901  1.000000  0.272997
2  0.643220  0.196134  0.341162
3  1.000000  0.912024  1.000000
4  0.534795  0.539653  0.482247
5 -0.110643  0.864838 -0.311395
6  0.698560 -0.383030  0.438125
7 -0.103575  0.735219 -0.074990
8 -0.633670  0.413587  0.077808
9 -1.000000 -1.000000 -1.000000