# Especialização em Ciência de Dados - Turma 2018.1 - Facens
## Aula 3 | Exercício 1

* **Data de entrega:** 28/out/2018 11:59 AM
* **Professor:**  Matheus Mota
* **Aluno:**  José Diniz Junior
* **RA:** 183134

# Questão única - Plotly Python

Utilizando um ou mais [datasets da disciplina](https://github.com/matheusmota/dataviz2018/tree/master/resources/datasets), usando o [Plotly Python](https://plot.ly/python/), construa:

* Um gráfico de linha
* Um gráfico de barras
* Um histograma
* Um gráfico radar
* Um gráfico de caixa
* Um gráfico de violino

Deixe claro qual o dataset escolhido e as variáveis.

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import plotly.figure_factory as ff

from plotly import tools
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected=True)

import plotly.offline as py

from IPython.core.pylabtools import figsize

# Leitura do DataSet 'cars.csv'

In [2]:
url ="https://raw.githubusercontent.com/matheusmota/dataviz2018/master/resources/datasets/cars.csv"
car = pd.read_csv(url, sep=',')
car.columns = car.columns.str.replace(' ', '_')
car.head()

   City_mpg          Classification  ...  Width  Year
0        18  Automatic transmission  ...    202  2009
1        22  Automatic transmission  ...    202  2009
2        21     Manual transmission  ...    202  2009
3        21  Automatic transmission  ...    202  2009
4        21  Automatic transmission  ...    202  2009

[5 rows x 18 columns]

## Alterado o valor de consumo (Highway_mpg) de 223 para 23 do veículo Chevrolet 6.0L 8 Cylinder 332 hp 367 ft-lbs Hybrid (index:3686), como o valor de consumo estava muito fora dos demais foi feito uma pesquisa e identificado que o consumo do mesmo estava errado no dataset.
 
#### fonte: https://cars.usnews.com/cars-trucks/chevrolet/silverado-1500-hybrid/2011

In [71]:
#car['Highway_mpg'].idxmax()#3686
cars = car.set_value(3686, 'Highway_mpg', 23)
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5076 entries, 0 to 5075
Data columns (total 19 columns):
City_mpg                   5076 non-null int64
Classification             5076 non-null object
Driveline                  5076 non-null object
Engine_Type                5076 non-null object
Fuel_Type                  5076 non-null object
Height                     5076 non-null int64
Highway_mpg                5076 non-null int64
Horsepower                 5076 non-null int64
Hybrid                     5076 non-null bool
ID                         5076 non-null object
Length                     5076 non-null int64
Make                       5076 non-null object
Model_Year                 5076 non-null object
Number_of_Forward_Gears    5076 non-null int64
Torque                     5076 non-null int64
Transmission               5076 non-null object
Width                      5076 non-null int64
Year                       5076 non-null int64
Cylinder                   5076 non-null object
dtypes: bool(1), int64(9), object(9)
memory usage: 718.8+ KB

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning:

set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

# Variáveis usadas nos gráficos

In [72]:
col_used = cars[['City_mpg','Classification','Horsepower','Highway_mpg','Make']]
col_used.head()

   City_mpg          Classification  Horsepower  Highway_mpg  Make
0        18  Automatic transmission         250           25  Audi
1        22  Automatic transmission         200           28  Audi
2        21     Manual transmission         200           30  Audi
3        21  Automatic transmission         200           28  Audi
4        21  Automatic transmission         200           28  Audi

# Gráfico de linha

In [9]:
marcas = pd.DataFrame(cars.Make.value_counts().reset_index(name='qtd').rename(columns={'index':'marcas'}))

trace = go.Scatter(x=marcas['marcas'],y=marcas['qtd'],mode = 'lines+markers')
data = [trace]
layout = go.Layout(
    title='Quantidade de veículos por marca',
    xaxis=dict(title='Marcas',titlefont=dict(size=20),tickangle=35),
    yaxis=dict(title='Quantidade',titlefont=dict(size=20)))
py.iplot(go.Figure(data = [trace], layout=layout))

# Gráfico de barras

In [76]:
tr = pd.DataFrame(cars.Classification.value_counts().reset_index(name='qtd').rename(columns={'index':'transmission'}))
trace = go.Bar(x=tr['transmission'],y=tr['qtd'])
data = [trace]
layout = go.Layout(
    title='Quantidade de veículos por transmissão',titlefont=dict(size=25),
    xaxis=dict(title='Transmissão',titlefont=dict(size=20)),
    yaxis=dict(title='Quantidade',titlefont=dict(size=20)))
py.iplot(go.Figure(data = [trace], layout=layout))

# Histograma

In [42]:
data = [go.Histogram(x=cars.Horsepower,nbinsx = 50)]
layout = dict(title='Histograma de potência dos veículos',titlefont=dict(size=25),
              xaxis= dict(title= 'Potência em cavalos',tickangle=25),
              yaxis = dict(title= 'Total de veículos'))

fig = dict(data = data, layout = layout)
iplot(fig)

In [55]:
cons_hwy = cars.Highway_mpg > 35
hwy = pd.DataFrame(cars[cons_hwy].Make.value_counts().nlargest(10).reset_index(name='qtd').rename(columns={'index':'marca'}))
hwy

        marca  qtd
0       Honda   40
1     Hyundai   25
2         Kia   20
3        Ford   16
4   Chevrolet   16
5  Volkswagen   12
6        MINI   11
7      Toyota    8
8       Mazda    6
9       Buick    4

In [56]:
cons_city = cars.City_mpg > 25
city = pd.DataFrame(cars[cons_city].Make.value_counts().nlargest(10).reset_index(name='qtd').rename(columns={'index':'marca'}))
city

        marca  qtd
0       Honda   48
1        MINI   38
2     Hyundai   36
3         Kia   33
4      Toyota   32
5   Chevrolet   28
6        Ford   16
7       Mazda   14
8  Volkswagen   12
9      Nissan   11

# Gráfico de radar 
## mostrar qual marca tem a maior quantidade de veículos que mais gastam em mpg(milhas por galão)

In [57]:
trace1 = go.Scatterpolar(
  r = city.qtd,
  theta = city.marca,
  fill = 'toself',
  name='Consumo na Cidade (mais que 25 mpg)'
)
trace2 = go.Scatterpolar(
  r = hwy.qtd,
  theta = hwy.marca,
  fill = 'toself',
    name='Consumo na Estrada (mais que 35 mpg)'
)
data = [trace1,trace2]

layout = go.Layout(
  title = "Quantidade de veículos por marca que mais gastam(10 maiores)",
  polar = dict(
    radialaxis = dict(
      visible = True,
      range = [0, 50]
    )
  ),
  showlegend = True
)

fig = go.Figure(data=data, layout=layout)
iplot(fig)

# Gráfico de caixa

In [33]:
trace1 = go.Box(y= cars.Highway_mpg,name='Consumo na estrada')
trace2 = go.Box(y= cars.City_mpg,name='Consumo na cidade')
data = [trace1,trace2]
layout = dict(title = 'Consumo MPG(Milhas por galão)',
              xaxis= dict(ticklen= 5,zeroline= False),
              yaxis = dict(title= 'Total de consumo',
                            ticks='outside',
                            tick0=0,
                            dtick=5,
                            ticklen=10,
                            tickwidth=2
                          ),
              boxmode='group'
             )
fig = go.Figure(data=data, layout=layout)
iplot(fig)

# Gráfico de violino

In [32]:
cons_h = cars.Highway_mpg
cons_c = cars.City_mpg
#cons_c.head()

In [31]:
fig = {
    "data": [{
            "type": 'violin',
            "y": cons_h,
            "name": 'consumo na estrada',
            "box": {"visible": True},
            "meanline": {"visible": True},
            "line": {"color": 'orange'}},
        {
            "type": 'violin',
            "y": cons_c,
            "name": 'consumo na cidade',
            "box": {"visible": True},
            "meanline": {"visible": True},
            "line": {"color": 'green'}
        }],
    "layout" : {"title": "Consumo em MPG na estrada e cidade", "yaxis": {"zeroline": False,},"violinmode": "group"}}
py.iplot(fig, filename = 'violin/multiple', validate = False)