<h1 align="center"> Aplicações em Processamento de Linguagem Natural </h1>
<h2 align="center"> Aula 03 - Técnicas de Pré-Processamento de Texto e Similaridade</h2>
<h3 align="center"> Prof. Fernando Vieira da Silva MSc.</h3>

<h2> Técnicas para Pré-Processamento - Parte 2</h2>

<p>Uma vez que o texto já foi devidamente tratado, removendo stopwords e pontuações, e aplicando stemming ou lemmatization, agora precisamos contar a frequência das palavras (ou n-grams) que utilizaremos em seguida como atributos para as técnicas de aprendizado de máquina.</p>

<b>1. TF-IDF (Term Frequency - Inverse Document Frequency)</b>

<p><b>Term Frequency:</b> um termo que aparece muito em um documento, tende a ser um termo importante. Em resumo, divide-se o número de vezes em que um termo apareceu pelo maior número de vezes em que algum outro termo apareceu no documento.</p>

tf<sub>wd</sub> = f<sub>wd</sub> / m<sub>wd</sub>

onde:<br>
f<sub>wd</sub> é o número de vezes em que o termo <i>w</i> aparece no documento <i>d</i>.<br>
m<sub>wd</sub> é o maior valor de f<sub>wd</sub> obtido para algum termo do documento <i>d</i><br>

<p><b>Inverse Document Frequency:</b> um termo que aparece em poucos documentos pode ser um bom descriminante. Obtem-se dividindo o número de documentos pelo número de documentos em que o termo aparece.</p>

idf<sub>w</sub> = log<sub>2</sub>(n / n<sub>w</sub>)

onde:<br>
n é o número de documentos no corpus
n<sub>w</sub> é o número de documentos em que o termo <i>w</i> aparece.

Na prática, usa-se:

tf-idf = tf<sub>wd</sub> * idf<sub>w</sub>

Podemos calcular o TF-IDF de um corpus usando o pacote <b>scikit-learn</b>. Primeiramente, vamos abrir novamente o texto de Hamlet e armazenar as sentenças em uma ndarray do numpy (como se cada sentença fosse um documento do corpus):

In [ ]:
import nltk
import numpy as np
from nltk.tokenize import sent_tokenize

hamlet_raw = nltk.corpus.gutenberg.raw('shakespeare-hamlet.txt')

sents = sent_tokenize(hamlet_raw)

hamlet_np = np.array(sents)

print(hamlet_np.shape)

In [ ]:
hamlet_np

<p>Agora vamos definir uma função para tokenização pelo scikit-learn.</p>

In [ ]:
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import string
from nltk.corpus import wordnet

stopwords_list = stopwords.words('english')

lemmatizer = WordNetLemmatizer()

def my_tokenizer(doc):
    words = word_tokenize(doc)
    
    pos_tags = pos_tag(words)
    
    non_stopwords = [w for w in pos_tags if not w[0].lower() in stopwords_list]
    
    non_punctuation = [w for w in non_stopwords if not w[0] in string.punctuation]
    
    lemmas = []
    for w in non_punctuation:
        if w[1].startswith('J'):
            pos = wordnet.ADJ
        elif w[1].startswith('V'):
            pos = wordnet.VERB
        elif w[1].startswith('N'):
            pos = wordnet.NOUN
        elif w[1].startswith('R'):
            pos = wordnet.ADV
        else:
            pos = wordnet.NOUN
        
        lemmas.append(lemmatizer.lemmatize(w[0], pos))

    return lemmas

E essa função será chamada pelo objeto TfidfVectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

hamlet_raw = nltk.corpus.gutenberg.raw('shakespeare-hamlet.txt')

sents = sent_tokenize(hamlet_raw)

hamlet_np = np.array(sents)

tfidf_vectorizer = TfidfVectorizer(tokenizer=my_tokenizer)

tfs = tfidf_vectorizer.fit_transform(hamlet_np)

print(tfs.shape)

In [ ]:
print([k for k in tfidf_vectorizer.vocabulary_.keys()][:20])

In [ ]:
print(tfs[:50,:50])#linha 0 coluna 17

<b>2. TF-IDF de N-gramas</b>

Opcionalmente, podemos obter os atributos tf-idf de n-grams, combinando as classes CountVectorizer e TfidfTransformer. Em nosso exemplo, vamos utilizar apenas trigramas:

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

count_vect = CountVectorizer(ngram_range=(3,3))

n_gram_counts = count_vect.fit_transform(hamlet_np)

tfidf_transformer = TfidfTransformer()

tfs_ngrams = tfidf_transformer.fit_transform(n_gram_counts)

print(tfs_ngrams.shape)

<b>3. Redução de Dimensionalidade</b>

<p>A transformação do corpus em atributos contendo as frequências TF-IDF em geral resultará numa ndarray bastante esparsa, ou seja, com muitas dimensões. Porém, além de isso tornar o treinamento de algoritmos mais demorado e custoso (computacionalmente falando), muitas dessas dimensões provavelmente são pouco representativas ou mesmo podem causar ruído durante o treinamento. Para resolver esse problema, podemos aplicar uma técnica de redução de dimensionalidade simples chamada <b>Singular Value Decomposition (SVD)</b>. 

<p>Essa técnica transformará os vetores da matriz original, rotacionando e escalando-os, resultando em novas representações. A redução de dimensionalidade é feita ao manter apenas as <i>k</i> dimensões mais representativas que escolhermos. Outra vantagem dessa técnica é que as dimensões originais são, de certa forma, "combinadas", o que resulta em uma nova forma de representar a combinação de termos. No contexto de PLN, essa técnica é conhecida como <b>Latent Semantic Analysis (LSA)</b></p>

In [ ]:
from sklearn.decomposition import TruncatedSVD

svd_transformer = TruncatedSVD(n_components=1000)

svd_transformer.fit(tfs)

print(sorted(svd_transformer.explained_variance_ratio_)[::-1][:30])#lista de variância dos componentes, os 30 primeiros

<p>Agora vamos manter as dimensões até que a variância acumulada seja maior ou igual a 0.50.</p>

In [ ]:
cummulative_variance = 0.0
k = 0
for var in sorted(svd_transformer.explained_variance_ratio_)[::-1]:
    cummulative_variance += var
    if cummulative_variance >= 0.5:
        break
    else:
        k += 1
        
print(k)#143 colunas

<p>Transformarmos novamente, mas desta vez com o número de k componentes que obtemos anteriormente.</p>

In [ ]:
svd_transformer = TruncatedSVD(n_components=k)
svd_data = svd_transformer.fit_transform(tfs)
print(sorted(svd_transformer.explained_variance_ratio_)[::-1])

In [ ]:
print(svd_data.shape)

In [ ]:
print(svd_data)

<h2> Similaridade de Cosseno</h2>

<p>Uma vez que dois documentos são representados como vetores numéricos, é possível comparar a similaridade entre os documentos ao calcular o cosseno do ângulo entre esses documentos - uma medida de distância, não de amplitude. Para isso, basta resolver a equação do produto escalar entre os vetores, para encontrar o cosseno.</p>

<img src="http://s0.wp.com/latex.php?latex=++%5Cdisplaystyle++%5Cvec%7Ba%7D+%5Ccdot+%5Cvec%7Bb%7D+%3D+%5C%7C%5Cvec%7Ba%7D%5C%7C%5C%7C%5Cvec%7Bb%7D%5C%7C%5Ccos%7B%5Ctheta%7D+%5C%5C+%5C%5C++%5Ccos%7B%5Ctheta%7D+%3D+%5Cfrac%7B%5Cvec%7Ba%7D+%5Ccdot+%5Cvec%7Bb%7D%7D%7B%5C%7C%5Cvec%7Ba%7D%5C%7C%5C%7C%5Cvec%7Bb%7D%5C%7C%7D++&amp;bg=ffffff&amp;fg=000000&amp;s=0" alt="  \displaystyle  \vec{a} \cdot \vec{b} = \|\vec{a}\|\|\vec{b}\|\cos{\theta} \\ \\  \cos{\theta} = \frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\|\|\vec{b}\|}  " title="  \displaystyle  \vec{a} \cdot \vec{b} = \|\vec{a}\|\|\vec{b}\|\cos{\theta} \\ \\  \cos{\theta} = \frac{\vec{a} \cdot \vec{b}}{\|\vec{a}\|\|\vec{b}\|}  " class="latex">

<img class=" wp-image-2582 " title="vector_space" src="http://blog.christianperone.com/wp-content/uploads/2013/09/vector_space.png" alt="" width="504" height="378">
<p fontsize=8>Fonte: http://blog.christianperone.com</p>

In [11]:
    documents = (
    "The sky is blue",
    "The sun is bright",
    "The sun in the sky is bright",
    "We can see the shining sun, the bright sun"
    )

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)
print(tfidf_matrix.shape)

(4, 11)

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

query_vect = tfidf_vectorizer.transform(["The sun is red in the sky"])#ele segmenta e tokeniza automático, mas é bom criar o próprio

cosine_similarity(query_vect, tfidf_matrix)#próx de um é mais similar, é a terceira frase

array([[0.55245238, 0.59222761, 0.9467919 , 0.37986898]])

In [ ]:
import numpy as np
desired_width = 320
pd.set_option('display.width', desired_width)
np.set_printoptions(linewidth=desired_width)
pd.set_option('display.max_columns',20)
pd.set_option('display.max_rows', None)

<p><b>Exercício 3:</b>Escreva um chatbot que, dado uma pergunta em Inglês, encontre uma pergunta mais parecida no corpus de perguntas e respostas disponível no Kaggle (https://www.kaggle.com/rtatman/questionanswer-dataset#S08_question_answer_pairs.txt) e exiba a resposta.

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../input/S08_question_answer_pairs.txt', sep='\t')
#df2 = df['ArticleTitle\tQuestion\tAnswer\tDifficultyFromQuestioner\tDifficultyFromAnswerer\tArticleFile']
df.head(100)

        ArticleTitle      ...        ArticleFile
0    Abraham_Lincoln      ...        S08_set3_a4
1    Abraham_Lincoln      ...        S08_set3_a4
2    Abraham_Lincoln      ...        S08_set3_a4
3    Abraham_Lincoln      ...        S08_set3_a4
4    Abraham_Lincoln      ...        S08_set3_a4
5    Abraham_Lincoln      ...        S08_set3_a4
6    Abraham_Lincoln      ...        S08_set3_a4
7    Abraham_Lincoln      ...        S08_set3_a4
8    Abraham_Lincoln      ...        S08_set3_a4
9    Abraham_Lincoln      ...        S08_set3_a4
10   Abraham_Lincoln      ...        S08_set3_a4
11   Abraham_Lincoln      ...        S08_set3_a4
12   Abraham_Lincoln      ...        S08_set3_a4
13   Abraham_Lincoln      ...        S08_set3_a4
14   Abraham_Lincoln      ...        S08_set3_a4
15   Abraham_Lincoln      ...        S08_set3_a4
16   Abraham_Lincoln      ...        S08_set3_a4
17   Abraham_Lincoln      ...        S08_set3_a4
18   Abraham_Lincoln      ...        S08_set3_a4
19   Abraham_Lincoln      ...        S08_set3_a4
20   Abraham_Lincoln      ...        S08_set3_a4
21   Abraham_Lincoln      ...        S08_set3_a4
22   Abraham_Lincoln      ...        S08_set3_a4
23   Abraham_Lincoln      ...        S08_set3_a4
24   Abraham_Lincoln      ...        S08_set3_a4
25   Abraham_Lincoln      ...        S08_set3_a4
26   Abraham_Lincoln      ...        S08_set3_a4
27   Abraham_Lincoln      ...        S08_set3_a4
28   Abraham_Lincoln      ...        S08_set3_a4
29   Abraham_Lincoln      ...        S08_set3_a4
..               ...      ...                ...
70  Alessandro_Volta      ...       S08_set4_a10
71  Alessandro_Volta      ...       S08_set4_a10
72  Alessandro_Volta      ...       S08_set4_a10
73  Alessandro_Volta      ...       S08_set4_a10
74  Alessandro_Volta      ...       S08_set4_a10
75  Alessandro_Volta      ...       S08_set4_a10
76  Alessandro_Volta      ...       S08_set4_a10
77  Alessandro_Volta      ...       S08_set4_a10
78   Amedeo_Avogadro      ...        S08_set4_a8
79   Amedeo_Avogadro      ...        S08_set4_a8
80   Amedeo_Avogadro      ...        S08_set4_a8
81   Amedeo_Avogadro      ...        S08_set4_a8
82   Amedeo_Avogadro      ...        S08_set4_a8
83   Amedeo_Avogadro      ...        S08_set4_a8
84   Amedeo_Avogadro      ...        S08_set4_a8
85   Amedeo_Avogadro      ...        S08_set4_a8
86   Amedeo_Avogadro      ...        S08_set4_a8
87   Amedeo_Avogadro      ...        S08_set4_a8
88   Amedeo_Avogadro      ...        S08_set4_a8
89   Amedeo_Avogadro      ...        S08_set4_a8
90   Amedeo_Avogadro      ...        S08_set4_a8
91   Amedeo_Avogadro      ...        S08_set4_a8
92   Amedeo_Avogadro      ...        S08_set4_a8
93   Amedeo_Avogadro      ...        S08_set4_a8
94   Amedeo_Avogadro      ...        S08_set4_a8
95   Amedeo_Avogadro      ...        S08_set4_a8
96   Amedeo_Avogadro      ...        S08_set4_a8
97   Amedeo_Avogadro      ...        S08_set4_a8
98   Amedeo_Avogadro      ...        S08_set4_a8
99   Amedeo_Avogadro      ...        S08_set4_a8

[100 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1715 entries, 0 to 1714
Data columns (total 6 columns):
ArticleTitle                1715 non-null object
Question                    1696 non-null object
Answer                      1475 non-null object
DifficultyFromQuestioner    1224 non-null object
DifficultyFromAnswerer      1473 non-null object
ArticleFile                 1713 non-null object
dtypes: object(6)
memory usage: 80.5+ KB

In [4]:
print('Antes:', df.shape)
df.drop_duplicates()
print('Depois:', df.shape)

Antes: (1715, 6)
Depois: (1715, 6)

In [5]:
df.isna().sum()

ArticleTitle                  0
Question                     19
Answer                      240
DifficultyFromQuestioner    491
DifficultyFromAnswerer      242
ArticleFile                   2
dtype: int64

In [6]:
df = df[['Question','Answer']]
df.head()

                                            Question Answer
0  Was Abraham Lincoln the sixteenth President of...    yes
1  Was Abraham Lincoln the sixteenth President of...   Yes.
2  Did Lincoln sign the National Banking Act of 1...    yes
3  Did Lincoln sign the National Banking Act of 1...   Yes.
4                   Did his mother die of pneumonia?     no

In [7]:
df.dropna(inplace=True)
df.isna().sum()

Question    0
Answer      0
dtype: int64

In [56]:
q = df.Question.tolist()
a = df.Answer.tolist()
q

['Was Abraham Lincoln the sixteenth President of the United States?',
 'Was Abraham Lincoln the sixteenth President of the United States?',
 'Did Lincoln sign the National Banking Act of 1863?',
 'Did Lincoln sign the National Banking Act of 1863?',
 'Did his mother die of pneumonia?',
 'Did his mother die of pneumonia?',
 "How many long was Lincoln's formal education?",
 "How many long was Lincoln's formal education?",
 'When did Lincoln begin his political career?',
 'When did Lincoln begin his political career?',
 'What did The Legal Tender Act of 1862 establish?',
 'What did The Legal Tender Act of 1862 establish?',
 'Who suggested Lincoln grow a beard?',
 'Who suggested Lincoln grow a beard?',
 'When did the Gettysburg address argue that America was born?',
 'When did the Gettysburg address argue that America was born?',
 'Did Lincoln beat John C. Breckinridge in the 1860 election?',
 'Did Lincoln beat John C. Breckinridge in the 1860 election?',
 'Was Abraham Lincoln the first President of the United States?',
 'Was Abraham Lincoln the first President of the United States?',
 'Did Lincoln start his political career in 1832?',
 'Did Lincoln start his political career in 1832?',
 'Did Lincoln ever represent Alton & Sangamon Railroad?',
 'Did Lincoln ever represent Alton & Sangamon Railroad?',
 'Which county was Lincoln born in?',
 'Which county was Lincoln born in?',
 'When did Lincoln first serve as President?',
 'When did Lincoln first serve as President?',
 'Who assassinated Lincoln?',
 'Who assassinated Lincoln?',
 'Did Lincoln win the election of 1860?',
 'Did Lincoln win the election of 1860?',
 'Who was the general in charge at the Battle of Antietam?',
 'Who was the general in charge at the Battle of Antietam?',
 'Why did Lincoln issue the Emancipation Proclamation?',
 'Why did Lincoln issue the Emancipation Proclamation?',
 'Do scholars rank lincoln among the top three presidents?',
 'Did lincoln have 18 months of schooling?',
 'Was Lincoln chosen as a presidential candidate in 1860?',
 'How old was Lincoln in 1816?',
 'When was the first photgraph of lincoln taken?',
 "How long was Lincoln's legal Career?",
 "What trail did Lincoln use a Farmers' Almanac in? ",
 'Did Abraham Lincoln live in the Frontier?',
 "Did Lincoln's Wife's Family support slavery?",
 'Who is most noted for his contributions to the theory of molarity and molecular weight?',
 'Who graduated in ecclesiastical law at the early age of 20 and began to practice?',
 'Who graduated in ecclesiastical law at the early age of 20 and began to practice?',
 'When did he publish another memoria?',
 'When did he become a professor?',
 'Is it true that he became a professor in 1820?',
 'Was Lorenzo Romano Amedeo Carlo Avogadro an Italian savant?',
 'Was Amedeo Avogadro born in Turin August 9th 1776 to a noble ancient family of Piedmont, Italy?',
 'Is he most noted for his contributions to the theory of molarity and molecular weight?',
 'Was King Victor Emmanuel III there to pay homage to Avogadro ?',
 "Is Avogadro 's number commonly used to compute the results of chemical reactions ?",
 'Did the scientific community not reserve great attention to his theory ?',
 'Was King Victor Emmanuel III there to pay homage to Avogadro ?',
 'Can the title of this famous 1811 paper be roughly translated into english?',
 'What happened in 1833?',
 'What happened in 1833?',
 'Who determined the dependence of the boiling of water with atmospheric pressure?',
 'What is named after him?',
 'When did he publish a collection?',
 'Is it true that he published a collection in 1738?',
 'Is it true that thermometer had 100 for the freezing point?',
 'Was Celsius born in Uppsala in Sweden?',
 'Was Anders Celsius (November 27, 1701 April 25, 1744) a Swedish astronomer?',
 'Is The Celsius crater on the Moon named after him?',
 'Who was the first to perform and publish careful experiments aiming at the definition of an international temperature scale on scientific grounds ?',
 'The Celsius crater on the Moon is what?',
 'Is the Celsius crater on the Moon named after him ?',
 'Had his thermometer 100 for the freezing point of water and 0 for the boiling point ?',
 'Was Celsius born in Uppsala in Sweden ?',
 'Is the Celsius crater on the Moon named after him ?',
 'Did he not determine the dependence of the boiling of water with atmospheric pressure -LRB- in excellent agreement with modern data -RRB- ?',
 'What happened from 1730 to 1744?',
 'What happened in 1745?',
 'Are beetles insects?',
 'Are beetles insects?',
 'Can beetles be found in polar regions?',
 'Can beetles be found in polar regions?',
 'Do beetles antennae function primarily as organs of smell?',
 'Do beetles antennae function primarily as organs of smell?',
 'What are the three sections of a beetle?',
 'What are the three sections of a beetle?',
 'Which defense mechanism uses colour or shape to deceive potential enemies?',
 'Which defense mechanism uses colour or shape to deceive potential enemies?',
 'Which type of beetle is a pest of potato plants?',
 'Which type of beetle is a pest of potato plants?',
 'How can beetle larvae be differentiated from other insect larvae?',
 'How can beetle larvae be differentiated from other insect larvae?',
 'What do beetles eat?',
 'What do beetles eat?',
 'What are the similarities between beetles and grasshoppers?',
 'What are the similarities between beetles and grasshoppers?',
 'Are certain species of beetles considered pests?',
 'Are certain species of beetles considered pests?',
 "Is a beetle's general anatomy uniform?",
 "Is a beetle's general anatomy uniform?",
 'Are beetles endopterygotes?',
 'Are beetles endopterygotes?',
 'How many species of beetles are there?',
 'How many species of beetles are there?',
 'When are sperm cells transferred to the female?',
 'When are sperm cells transferred to the female?',
 'What is the study of beetles called?',
 'What is the study of beetles called?',
 'Is it possible that there are more than 350,000 species of beetles?',
 'Is it possible that there are more than 350,000 species of beetles?',
 'Is the Adephaga suborder larger than the Polyphaga suborder?',
 'Is the Adephaga suborder larger than the Polyphaga suborder?',
 'Do carrion beetles eat dung?',
 'Do carrion beetles eat dung?',
 'What are prey of various animals including birds and mammals?',
 'What was given by Aristotle for the hardened shield like forewings?',
 'Who or what vary greatly in form within the coleoptera?',
 'Are many beetles territorial?',
 'Are beetles endopterygotes with complete metamorphosis?',
 'Oxygen is what?',
 'Is there a thriving industry in the collection of beetle specimens for amateur and professional collectors ?',
 'Have coleopterists formed organisations to facilitate the study of beetles ?',
 'Is the study of beetles called coleopterology , and its practitioners are coleopterists ?',
 'May a single female lay from several dozen to several thousand eggs during her lifetime ?',
 'Can beetles be found in almost all habitats?',
 'What happened on plants and fungi?',
 'Was Calvin Coolidge the twenty-ninth vice president?',
 'Was Calvin Coolidge the twenty-ninth vice president?',
 'Was Calvin Coolidge born in Plymouth, Windsor County, Vermont?',
 'Was Calvin Coolidge born in Plymouth, Windsor County, Vermont?',
 'Did Coolidge graduate from Black River Academy?',
 'Did Coolidge graduate from Black River Academy?',
 'When did he drop John from his name?',
 'When did he drop John from his name?',
 'When did Coolidge meet and marry Grace Anna Goodhue?',
 'When did Coolidge meet and marry Grace Anna Goodhue?',
 "What period of rapid economic growth did the United States experience during Coolidge's presidency?",
 "What period of rapid economic growth did the United States experience during Coolidge's presidency?",
 'What did Coolidge do after graduating from Amherst?',
 'What did Coolidge do after graduating from Amherst?',
 'Of what state was Coolidge governor?',
 'Who appointed Harlan Fiske Stone to the Supreme Court?',
 'Who appointed Harlan Fiske Stone to the Supreme Court?',
 'Was Coolidge the thirteenth President of the United States?',
 'Was Coolidge the thirteenth President of the United States?',
 'Was Calvin Coolidge Republican?',
 'Was Calvin Coolidge Republican?',
 'Was Calvin Coolidge a governor of MassachuS08_setts?',
 'Was Calvin Coolidge a governor of MassachuS08_setts?',
 'When was Coolidge born?',
 'When was Coolidge born?',
 "Where did Coolidge's grandfather had government offices?",
 "Where did Coolidge's grandfather had government offices?",
 'Which state were Coolidge born in?',
 'Which state were Coolidge born in?',
 'Is Calvin Jr. older than John Coolidge?',
 'Is Calvin Jr. older than John Coolidge?',
 'Did Coolidge get in Amherst College?',
 'Did Coolidge get in Amherst College?',
 "What caused Calvin Jr.'s death?",
 "What caused Calvin Jr.'s death?",
 'Was John Calvin Coolidge Jr. was born in Las Vegas?',
 'Was John Calvin Coolidge Jr. was born in Las Vegas?',
 'Was Coolidge opposed in the Republican nomination for Governor of MassachuS08_setts in 1918?',
 'Was Coolidge opposed in the Republican nomination for Governor of MassachuS08_setts in 1918?',
 'Did Coolidge meet and marry Grace Anna Goodhue?',
 'Did Coolidge meet and marry Grace Anna Goodhue?',
 'What year did Coolidge open his own law office?',
 'What year did Coolidge open his own law office?',
 'What fraternity was Coolidge a member of?',
 'What fraternity was Coolidge a member of?',
 'In 1905 Coolidge met and married whom?',
 'In 1905 Coolidge met and married whom?',
 'Why did Coolidge not attend law school?',
 'Why did Coolidge not attend law school?',
 'Have there been other US presidents that have visited Cuba?',
 'Have there been other US presidents that have visited Cuba?',
 "What years were Coolidge's two sons born in?",
 "What years were Coolidge's two sons born in?",
 'Did France cede nearly all of its colonies in Europe in 1763?',
 'Did France cede nearly all of its colonies in Europe in 1763?',
 'Is Canada a member of the OECD?',
 'Is Canada a member of the OECD?',
 "Is Canada's official language Zulu?",
 "Is Canada's official language Zulu?",
 'What is one significant non-official language?',
 'What is one significant non-official language?',
 'In addition to Port Royal, where else did Samuel de Champlain establish a S08_settlement?',
 'What was the Consitution Act formerly called?',
 'What was the Consitution Act formerly called?',
 'Which countries established colonies in Canada?',
 'Which countries established colonies in Canada?',
 'How has Canada helped UN peacekeeping efforts?',
 'How has Canada helped UN peacekeeping efforts?',
 "What percentage of the population don't speak English or French at home?",
 "What percentage of the population don't speak English or French at home?",
 'Is Canada bilingual?',
 'Is Canada bilingual?',
 'Did Canadian soldiers win the Battle of Vimy Ridge in 1917?',
 'Did Canadian soldiers win the Battle of Vimy Ridge in 1917?',
 'Is an official language of Canada German?',
 'Is an official language of Canada German?',
 'How many provinces and territories does Canada have?',
 'How many provinces and territories does Canada have?',
 "What is Canada's national unemployment rate?",
 "What is Canada's national unemployment rate?",
 'Where is the most densely populated part of Canada?',
 'Where is the most densely populated part of Canada?',
 'What is the largest country in the world?',
 'What is the largest country in the world?',
 'What is the largest religious group in Canada?',
 'What is the largest religious group in Canada?',
 'When did Canada have one of the largest armed forces in the world?',
 'When did Canada have one of the largest armed forces in the world?',
 'What have been inhabited for millennia by aboriginal peoples?',
 'European books and maps began referring to this region as Canada in what year?',
 "What was Canada's most important industry until the 1800s?",
 'Is it true that it angered many residents of the thirteen colonies?',
 'How do cuba and declining participation relate?',
 'Is it true that provinces have a large degree of autonomy?',
 'What did Canada adopt in 1965?',
 'What arrived in Britain?',
 "Are Canada 's two official languages English and French ?",
 "Are Canada 's official national sports ice hockey ( winter ) and lacrosse ( summer ) ?",
 'Is Canada a geographically vast and ethnically diverse country ?',
 'Did Mainland Nova Scotia not come under British rule with the Treaty of Utrecht    (: ; ?',
 "Did Cartier not use the word ` Canada ' to refer to not only that village , but the entire area subject to Donnacona , Chief at Stadacona ?",
 'Did continental European immigrants not S08_settle the prairies ?',
 "Is it the world 's second largest country by total area?",
 'What happened in 1867?',
 'Are ducks in the Arctic Northern Hemisphere migratory?',
 'Are ducks in the Arctic Northern Hemisphere migratory?',
 'Is a drake a male?',
 'Is a drake a male?',
 'Do all ducks "quack"?',
 'Do all ducks "quack"?',
 'What is the name of a specialized species of duck adapted to catch large fish?',
 'What animal attracts the most humor and silliness?',
 'What animal attracts the most humor and silliness?',
 'What is an economic use of a duck?',
 'What is an economic use of a duck?',
 'Who is Daffy Duck?',
 'Who is Daffy Duck?',
 'What makes it more difficult for a diving duck to fly?',
 'What makes it more difficult for a diving duck to fly?',
 'What are the reasons for hunting wild ducks?',
 'Do ducks forage underwater?',
 'Do ducks forage underwater?',
 'Do all ducks "quack"?',
 'Do all ducks "quack"?',
 'Is foie gras often made from ducks?',
 'Is foie gras often made from ducks?',
 'What economic uses to ducks have?',
 'What economic uses to ducks have?',
 'What kind of ducks feed on land?',
 'What kind of ducks feed on land?',
 'What unrelated water birds are ducks sometimes confused with?',
 'What unrelated water birds are ducks sometimes confused with?',
 'What does the word duck mean?',
 'What does the word duck mean?',
 'What are some common predators of ducks?',
 'What are some common predators of ducks?',
 "How does a Mallard's tongue work?",
 "How does a Mallard's tongue work?",
 'Are diving ducks heavier tha dabbling ducks?',
 'Are diving ducks heavier tha dabbling ducks?',
 'Are adult ducks fast fliers?',
 'Are adult ducks fast fliers?',
 'Are ducks an accepted presence in some populated areas?',
 'Are ducks an accepted presence in some populated areas?',
 'What types of unrelated water birds with similar forms are ducks sometimes confused with?',
 'What types of unrelated water birds with similar forms are ducks sometimes confused with?',
 'Why are ducklings particularly vulnerable?',
 'Why are ducklings particularly vulnerable?',
 'What are some economic uses for duck?',
 'What are some economic uses for duck?',
 'What allows a duck to filter water out of the side of their beaks and keep food inside?',
 'What allows a duck to filter water out of the side of their beaks and keep food inside?',
 'What expression is part of a conceptual framework for testing computer systems?',
 'What expression is part of a conceptual framework for testing computer systems?',
 'Where did the expression "a sitting duck" come from?',
 'Where did the expression "a sitting duck" come from?',
 'Is Egypt bordered by the Gaza Strip?',
 'Is Egypt bordered by the Gaza Strip?',
 'Is Egypt the most populated country in Africa?',
 'Is Egypt the most populated country in Africa?',
 'Does Egypt have political influence in the Middle East?',
 'Does Egypt have political influence in the Middle East?',
 'When was the Six Day War?',
 'When was the Six Day War?',
 'What religions has Egypt outlawed?',
 'What religions has Egypt outlawed?',
 'What is the poulation of Egypt?',
 'What is the poulation of Egypt?',
 "Why does most of Egypt's population live near the Nile?",
 "Why does most of Egypt's population live near the Nile?",
 'Are there a large number of Jews living in Egypt today?',
 'Are there a large number of Jews living in Egypt today?',
 'During what period was Akhenaten a Pharaoh?',
 'During what period was Akhenaten a Pharaoh?',
 'Is Egypt in Asia?',
 'Does Egypt receive the least rainfall in the world?',
 'Does Egypt receive the least rainfall in the world?',
 "Does Egypt's foreign policy operates along moderate lines?",
 "Does Egypt's foreign policy operates along moderate lines?",
 'Since when has Egypt been a republic?',
 'Since when has Egypt been a republic?',
 'When were the Great Sphinx and the Pyramids of Giza built?',
 'When were the Great Sphinx and the Pyramids of Giza built?',
 'What countries border Egypt?',
 'What countries border Egypt?',
 'What is the estimated population of Egypt?',
 'What is the estimated population of Egypt?',
 'Does snow fall in Egypt?',
 'Does snow fall in Egypt?',
 'When did organized agriculture appear in the Nile Valley?',
 'When did organized agriculture appear in the Nile Valley?',
 'Are elephants the largest land animals alive today?',
 'Are elephants the largest land animals alive today?',
 'Can an elephant kill a rhinoceros?',
 'Can an elephant kill a rhinoceros?',
 'Are elephants good swimmers?',
 'Are elephants good swimmers?',
 'How many living species of African Elephants are there?',
 'How many living species of African Elephants are there?',
 'How long may elephants live?',
 'How long may elephants live?',
 "Why does the phrase 'elephants never forget' have no metaphorical meaning?",
 "Why does the phrase 'elephants never forget' have no metaphorical meaning?",
 'How many living species of Asian Elephants are there?',
 'How many living species of Asian Elephants are there?',
 'How much do elephants weight at birth?',
 'How much do elephants weight at birth?',
 'What did Aristotle say about elephants?',
 'What did Aristotle say about elephants?',
 'Are elephant populations in West Africa generally small and fragmented?',
 'Are elephant populations in West Africa generally small and fragmented?',
 'Is the Asian elephant larger than the African?',
 'Is the Asian elephant larger than the African?',
 "Is an elephant's skin tough?",
 "Is an elephant's skin tough?",
 'How do elephants communicate over long distances?',
 'How do elephants communicate over long distances?',
 'When do African elephants lie down?',
 "How long is the elephant's gestation period?",
 "How long is the elephant's gestation period?",
 'How many species of African elephants have been proposed?',
 'How many species of African elephants have been proposed?',
 "What are the elephant's ears important for?",
 "What are the elephant's ears important for?",
 'What land animal has the largest brain?',
 'What land animal has the largest brain?',
 'Are elephants mammals?',
 'Are elephants mammals?',
 'Have elephants been used as working animals?',
 'Have elephants been used as working animals?',
 'Do they prefer forested areas?',
 'Do they prefer forested areas?',
 'What is the world population of Asian elephants?',
 'What is the world population of Asian elephants?',
 'What part of an elephant is very important for temperature regulation?',
 'What part of an elephant is very important for temperature regulation?',
 'Where was the largest elephant ever recorded shot?',
 'Where was the largest elephant ever recorded shot?',
 'Is an Asian elephant smaller than an African elephant?',
 'Is an Asian elephant smaller than an African elephant?',
 'What land animal is larger than an elephant?',
 'What land animal is larger than an elephant?',
 'Has tusklessness become a rare abnormality?',
 'Has tusklessness become a rare abnormality?',
 'Were the treaties signed in 1947 and 1948 with the Ukraine?',
 'Were the treaties signed in 1947 and 1948 with the Ukraine?',
 'Is Finnish a member of the Baltic-Finnic subgroup of the Uralic languages?',

In [9]:
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import string
from nltk.corpus import wordnet

stopwords_list = stopwords.words('english')

lemmatizer = WordNetLemmatizer()

def my_tokenizer(doc):
    words = word_tokenize(doc)
    
    pos_tags = pos_tag(words)
    
    non_stopwords = [w for w in pos_tags if not w[0].lower() in stopwords_list]
    
    non_punctuation = [w for w in non_stopwords if not w[0] in string.punctuation]
    
    lemmas = []
    for w in non_punctuation:
        if w[1].startswith('J'):
            pos = wordnet.ADJ
        elif w[1].startswith('V'):
            pos = wordnet.VERB
        elif w[1].startswith('N'):
            pos = wordnet.NOUN
        elif w[1].startswith('R'):
            pos = wordnet.ADV
        else:
            pos = wordnet.NOUN
        
        lemmas.append(lemmatizer.lemmatize(w[0], pos))

    return lemmas

In [57]:
#tok = sent_tokenize(q)
qn = np.array(q)
qn[0]

'Was Abraham Lincoln the sixteenth President of the United States?'

In [44]:
#tok = sent_tokenize(q)
tfidf_vectorizer_q = TfidfVectorizer(tokenizer=my_tokenizer)
tfidf_matrix_q = tfidf_vectorizer.fit_transform(q)
print(tfidf_matrix_q.shape)

(1475, 1958)

In [45]:
tfidf_vectorizer_a = TfidfVectorizer(tokenizer=my_tokenizer)
tfidf_matrix_a = tfidf_vectorizer.fit_transform(a)
print(tfidf_matrix_a.shape)

(1475, 1484)

In [67]:
from sklearn.decomposition import TruncatedSVD

svd_transformer = TruncatedSVD(n_components=1000)

svd_transformer.fit(tfidf_matrix_a)

print(sorted(svd_transformer.explained_variance_ratio_)[::-1][:30])#lista de variância dos componentes, os 30 primeiros

[0.2789655209987825, 0.005432411068845237, 0.004468005849943647, 0.00408689543602438, 0.004083392072237264, 0.004082093797454486, 0.004075645906725975, 0.003923800562888356, 0.0038808261640369108, 0.003867616941249538, 0.0038292328046277183, 0.003743845572787127, 0.0036380786151258494, 0.0036207853896607647, 0.0034697598339999518, 0.003424992898232647, 0.003418842680841326, 0.003410805730315657, 0.0034090085700726144, 0.00338617890677555, 0.003375660933166749, 0.0033409048855112815, 0.0032944255458493216, 0.0032291715275325093, 0.0031717360593734607, 0.003130990383760177, 0.003068376469042071, 0.003001713246613605, 0.0029882592712896514, 0.002950768705626418]

In [70]:
print(svd_transformer.shape)

AttributeError: 'TruncatedSVD' object has no attribute 'shape'

In [37]:
print([k for k in tfidf_vectorizer.vocabulary_.keys()][:100])

['abraham', 'lincoln', 'sixteenth', 'president', 'united', 'state', 'sign', 'national', 'banking', 'act', '1863', 'mother', 'die', 'pneumonia', 'many', 'long', "'s", 'formal', 'education', 'begin', 'political', 'career', 'legal', 'tender', '1862', 'establish', 'suggest', 'grow', 'beard', 'gettysburg', 'address', 'argue', 'america', 'bear', 'beat', 'john', 'c.', 'breckinridge', '1860', 'election', 'first', 'start', '1832', 'ever', 'represent', 'alton', 'sangamon', 'railroad', 'county', 'born', 'serve', 'assassinate', 'win', 'general', 'charge', 'battle', 'antietam', 'issue', 'emancipation', 'proclamation', 'scholar', 'rank', 'among', 'top', 'three', '18', 'month', 'school', 'chosen', 'presidential', 'candidate', 'old', '1816', 'photgraph', 'take', 'trail', 'use', 'farmer', 'almanac', 'live', 'frontier', 'wife', 'family', 'support', 'slavery', 'noted', 'contribution', 'theory', 'molarity', 'molecular', 'weight', 'graduate', 'ecclesiastical', 'law', 'early', 'age', '20', 'practice', 'publish', 'another']

In [36]:
print(tfidf_matrix[:50,:50])#linha 0 coluna 17

  (2, 46)	0.47386733330505154
  (3, 46)	0.47386733330505154
  (6, 4)	0.24857998835147035
  (7, 4)	0.24857998835147035
  (10, 45)	0.48160953324253425
  (11, 45)	0.48160953324253425
  (16, 44)	0.3962093491634134
  (17, 44)	0.3962093491634134
  (20, 40)	0.5106893054831116
  (21, 40)	0.5106893054831116
  (30, 44)	0.5747922418515101
  (31, 44)	0.5747922418515101
  (37, 30)	0.6013209916013743
  (38, 44)	0.44959497433572787
  (39, 35)	0.708799967800982
  (41, 4)	0.26813377615268247
  (44, 4)	0.43741259135279054

In [66]:
#tfidf_vectorizer_q = TfidfVectorizer(tokenizer=my_tokenizer)
tfidf_matrix_q = tfidf_vectorizer.fit_transform(['Was Abraham Lincoln the sixteenth President of the United States?'])
cosine_similarity(tfidf_matrix_q, tfidf_matrix_a)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 6 while Y.shape[1] == 1484

In [15]:
tfidf_matrix

<4x11 sparse matrix of type '<class 'numpy.float64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [21]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
#from nltk.tokenize import sent_tokenize

hamlet_raw = nltk.corpus.gutenberg.raw('shakespeare-hamlet.txt')

sents = sent_tokenize(hamlet_raw)

hamlet_np = np.array(sents)

tfidf_vectorizer = TfidfVectorizer(tokenizer=my_tokenizer)

tfs = tfidf_vectorizer.fit_transform(hamlet_np)

print(tfs.shape)

(2355, 4305)

In [24]:
hamlet_raw

"[The Tragedie of Hamlet by William Shakespeare 1599]\n\n\nActus Primus. Scoena Prima.\n\nEnter Barnardo and Francisco two Centinels.\n\n  Barnardo. Who's there?\n  Fran. Nay answer me: Stand & vnfold\nyour selfe\n\n   Bar. Long liue the King\n\n   Fran. Barnardo?\n  Bar. He\n\n   Fran. You come most carefully vpon your houre\n\n   Bar. 'Tis now strook twelue, get thee to bed Francisco\n\n   Fran. For this releefe much thankes: 'Tis bitter cold,\nAnd I am sicke at heart\n\n   Barn. Haue you had quiet Guard?\n  Fran. Not a Mouse stirring\n\n   Barn. Well, goodnight. If you do meet Horatio and\nMarcellus, the Riuals of my Watch, bid them make hast.\nEnter Horatio and Marcellus.\n\n  Fran. I thinke I heare them. Stand: who's there?\n  Hor. Friends to this ground\n\n   Mar. And Leige-men to the Dane\n\n   Fran. Giue you good night\n\n   Mar. O farwel honest Soldier, who hath relieu'd you?\n  Fra. Barnardo ha's my place: giue you goodnight.\n\nExit Fran.\n\n  Mar. Holla Barnardo\n\n   Bar. Say, what is Horatio there?\n  Hor. A peece of him\n\n   Bar. Welcome Horatio, welcome good Marcellus\n\n   Mar. What, ha's this thing appear'd againe to night\n\n   Bar. I haue seene nothing\n\n   Mar. Horatio saies, 'tis but our Fantasie,\nAnd will not let beleefe take hold of him\nTouching this dreaded sight, twice seene of vs,\nTherefore I haue intreated him along\nWith vs, to watch the minutes of this Night,\nThat if againe this Apparition come,\nHe may approue our eyes, and speake to it\n\n   Hor. Tush, tush, 'twill not appeare\n\n   Bar. Sit downe a-while,\nAnd let vs once againe assaile your eares,\nThat are so fortified against our Story,\nWhat we two Nights haue seene\n\n   Hor. Well, sit we downe,\nAnd let vs heare Barnardo speake of this\n\n   Barn. Last night of all,\nWhen yond same Starre that's Westward from the Pole\nHad made his course t' illume that part of Heauen\nWhere now it burnes, Marcellus and my selfe,\nThe Bell then beating one\n\n   Mar. Peace, breake thee of:\nEnter the Ghost.\n\nLooke where it comes againe\n\n   Barn. In the same figure, like the King that's dead\n\n   Mar. Thou art a Scholler; speake to it Horatio\n\n   Barn. Lookes it not like the King? Marke it Horatio\n\n   Hora. Most like: It harrowes me with fear & wonder\n  Barn. It would be spoke too\n\n   Mar. Question it Horatio\n\n   Hor. What art thou that vsurp'st this time of night,\nTogether with that Faire and Warlike forme\nIn which the Maiesty of buried Denmarke\nDid sometimes march: By Heauen I charge thee speake\n\n   Mar. It is offended\n\n   Barn. See, it stalkes away\n\n   Hor. Stay: speake; speake: I Charge thee, speake.\n\nExit the Ghost.\n\n  Mar. 'Tis gone, and will not answer\n\n   Barn. How now Horatio? You tremble & look pale:\nIs not this something more then Fantasie?\nWhat thinke you on't?\n  Hor. Before my God, I might not this beleeue\nWithout the sensible and true auouch\nOf mine owne eyes\n\n   Mar. Is it not like the King?\n  Hor. As thou art to thy selfe,\nSuch was the very Armour he had on,\nWhen th' Ambitious Norwey combatted:\nSo frown'd he once, when in an angry parle\nHe smot the sledded Pollax on the Ice.\n'Tis strange\n\n   Mar. Thus twice before, and iust at this dead houre,\nWith Martiall stalke, hath he gone by our Watch\n\n   Hor. In what particular thought to work, I know not:\nBut in the grosse and scope of my Opinion,\nThis boades some strange erruption to our State\n\n   Mar. Good now sit downe, & tell me he that knowes\nWhy this same strict and most obseruant Watch,\nSo nightly toyles the subiect of the Land,\nAnd why such dayly Cast of Brazon Cannon\nAnd Forraigne Mart for Implements of warre:\nWhy such impresse of Ship-wrights, whose sore Taske\nDo's not diuide the Sunday from the weeke,\nWhat might be toward, that this sweaty hast\nDoth make the Night ioynt-Labourer with the day:\nWho is't that can informe me?\n  Hor. That can I,\nAt least the whisper goes so: Our last King,\nWhose Image euen but now appear'd to vs,\nWas (as you know) by Fortinbras of Norway,\n(Thereto prick'd on by a most emulate Pride)\nDar'd to the Combate. In which, our Valiant Hamlet,\n(For so this side of our knowne world esteem'd him)\nDid slay this Fortinbras: who by a Seal'd Compact,\nWell ratified by Law, and Heraldrie,\nDid forfeite (with his life) all those his Lands\nWhich he stood seiz'd on, to the Conqueror:\nAgainst the which, a Moity competent\nWas gaged by our King: which had return'd\nTo the Inheritance of Fortinbras,\nHad he bin Vanquisher, as by the same Cou'nant\nAnd carriage of the Article designe,\nHis fell to Hamlet. Now sir, young Fortinbras,\nOf vnimproued Mettle, hot and full,\nHath in the skirts of Norway, heere and there,\nShark'd vp a List of Landlesse Resolutes,\nFor Foode and Diet, to some Enterprize\nThat hath a stomacke in't: which is no other\n(And it doth well appeare vnto our State)\nBut to recouer of vs by strong hand\nAnd termes Compulsatiue, those foresaid Lands\nSo by his Father lost: and this (I take it)\nIs the maine Motiue of our Preparations,\nThe Sourse of this our Watch, and the cheefe head\nOf this post-hast, and Romage in the Land.\nEnter Ghost againe.\n\nBut soft, behold: Loe, where it comes againe:\nIle crosse it, though it blast me. Stay Illusion:\nIf thou hast any sound, or vse of Voyce,\nSpeake to me. If there be any good thing to be done,\nThat may to thee do ease, and grace to me; speak to me.\nIf thou art priuy to thy Countries Fate\n(Which happily foreknowing may auoyd) Oh speake.\nOr, if thou hast vp-hoorded in thy life\nExtorted Treasure in the wombe of Earth,\n(For which, they say, you Spirits oft walke in death)\nSpeake of it. Stay, and speake. Stop it Marcellus\n\n   Mar. Shall I strike at it with my Partizan?\n  Hor. Do, if it will not stand\n\n   Barn. 'Tis heere\n\n   Hor. 'Tis heere\n\n   Mar. 'Tis gone.\n\nExit Ghost.\n\nWe do it wrong, being so Maiesticall\nTo offer it the shew of Violence,\nFor it is as the Ayre, invulnerable,\nAnd our vaine blowes, malicious Mockery\n\n   Barn. It was about to speake, when the Cocke crew\n\n   Hor. And then it started, like a guilty thing\nVpon a fearfull Summons. I haue heard,\nThe Cocke that is the Trumpet to the day,\nDoth with his lofty and shrill-sounding Throate\nAwake the God of Day: and at his warning,\nWhether in Sea, or Fire, in Earth, or Ayre,\nTh' extrauagant, and erring Spirit, hyes\nTo his Confine. And of the truth heerein,\nThis present Obiect made probation\n\n   Mar. It faded on the crowing of the Cocke.\nSome sayes, that euer 'gainst that Season comes\nWherein our Sauiours Birch is celebrated,\nThe Bird of Dawning singeth all night long:\nAnd then (they say) no Spirit can walke abroad,\nThe nights are wholsome, then no Planets strike,\nNo Faiery talkes, nor Witch hath power to Charme:\nSo hallow'd, and so gracious is the time\n\n   Hor. So haue I heard, and do in part beleeue it.\nBut looke, the Morne in Russet mantle clad,\nWalkes o're the dew of yon high Easterne Hill,\nBreake we our Watch vp, and by my aduice\nLet vs impart what we haue seene to night\nVnto yong Hamlet. For vpon my life,\nThis Spirit dumbe to vs, will speake to him:\nDo you consent we shall acquaint him with it,\nAs needfull in our Loues, fitting our Duty?\n  Mar. Let do't I pray, and I this morning know\nWhere we shall finde him most conueniently.\n\nExeunt.\n\nScena Secunda.\n\nEnter Claudius King of Denmarke, Gertrude the Queene, Hamlet,\nPolonius,\nLaertes, and his Sister Ophelia, Lords Attendant.\n\n  King. Though yet of Hamlet our deere Brothers death\nThe memory be greene: and that it vs befitted\nTo beare our hearts in greefe, and our whole Kingdome\nTo be contracted in one brow of woe:\nYet so farre hath Discretion fought with Nature,\nThat we with wisest sorrow thinke on him,\nTogether with remembrance of our selues.\nTherefore our sometimes Sister, now our Queene,\nTh' imperiall Ioyntresse of this warlike State,\nHaue we, as 'twere, with a defeated ioy,\nWith one Auspicious, and one Dropping eye,\nWith mirth in Funerall, and with Dirge in Marriage,\nIn equall Scale weighing Delight and Dole\nTaken to Wife; nor haue we heerein barr'd\nYour better Wisedomes, which haue freely gone\nWith this affaire along, for all our Thankes.\nNow followes, that you know young Fortinbras,\nHolding a weake supposall of our worth;\nOr thinking by our late deere Brothers death,\nOur State to be disioynt, and out of Frame,\nColleagued with the dreame of his Aduantage;\nHe hath not fayl'd to pester vs with Message,\nImporting the surrender of those Lands\nLost by his Father: with all Bonds of Law\nTo our most valiant Brother. So much for him.\nEnter Voltemand and Cornelius.\n\nNow for our selfe, and for this time of meeting\nThus much the businesse is. We haue heere writ\nTo Norway, Vncle of young Fortinbras,\nWho Impotent and Bedrid, scarsely heares\nOf this his Nephewes purpose, to suppresse\nHis further gate heerein. In that the Leuies,\nThe Lists, and full proportions are all made\nOut of his subiect: and we heere dispatch\nYou good Cornelius, and you Voltemand,\nFor bearing of this greeting to old Norway,\nGiuing to you no further personall power\nTo businesse with the King, more then the scope\nOf these dilated Articles allow:\nFarewell, and let your hast commend your duty\n\n   Volt. In that, and all things, will we shew our duty\n\n   King. We doubt it nothing, heartily farewell.\n\nExit Voltemand and Cornelius.\n\nAnd now Laertes, what's the newes with you?\nYou told vs of some suite. What is't Laertes?\nYou cannot speake of Reason to the Dane,\nAnd loose your voyce. What would'st thou beg Laertes,\nThat shall not be my Offer, not thy Asking?\nThe Head is not more Natiue to the Heart,\nThe Hand more instrumentall to the Mouth,\nThen is the Throne of Denmarke to thy Father.\nWhat would'st thou haue Laertes?\n  Laer. Dread my Lord,\nYour leaue and fauour to returne to France,\nFrom whence, though willingly I came to Denmarke\nTo shew my duty in your Coronation,\nYet now I must confesse, that duty done,\nMy thoughts and wishes bend againe towards France,\nAnd bow them to your gracious leaue and pardon\n\n   King. Haue you your Fathers leaue?\nWhat sayes Pollonius?\n  Pol. He hath my Lord:\nI do beseech you giue him leaue to go\n\n   King. Take thy faire houre Laertes, time be thine,\nAnd thy best graces spend it at thy will:\nBut now my Cosin Hamlet, and my Sonne?\n  Ham. A little more then kin, and lesse then kinde\n\n   King. How is it that the Clouds still hang on you?\n  Ham. Not so my Lord, I am too much i'th' Sun\n\n   Queen. Good Hamlet cast thy nightly colour off,\nAnd let thine eye looke like a Friend on Denmarke.\nDo not for euer with thy veyled lids\nSeeke for thy Noble Father in the dust;\nThou know'st 'tis common, all that liues must dye,\nPassing through Nature, to Eternity\n\n   Ham. I Madam, it is common\n\n   Queen. If it be;\nWhy seemes it so particular with thee\n\n   Ham. Seemes Madam? Nay, it is: I know not Seemes:\n'Tis not alone my Inky Cloake (good Mother)\nNor Customary suites of solemne Blacke,\nNor windy suspiration of forc'd breath,\nNo, nor the fruitfull Riuer in the Eye,\nNor the deiected hauiour of the Visage,\nTogether with all Formes, Moods, shewes of Griefe,\nThat can denote me truly. These indeed Seeme,\nFor they are actions that a man might play:\nBut I haue that Within, which passeth show;\nThese, but the Trappings, and the Suites of woe\n\n   King. 'Tis sweet and commendable\nIn your Nature Hamlet,\nTo giue these mourning duties to your Father:\nBut you must know, your Father lost a Father,\nThat Father lost, lost his, and the Suruiuer bound\nIn filiall Obligation, for some terme\nTo do obsequious Sorrow. But to perseuer\nIn obstinate Condolement, is a course\nOf impious stubbornnesse. 'Tis vnmanly greefe,\nIt shewes a will most incorrect to Heauen,\nA Heart vnfortified, a Minde impatient,\nAn Vnderstanding simple, and vnschool'd:\nFor, what we know must be, and is as common\nAs any the most vulgar thing to sence,\nWhy should we in our peeuish Opposition\nTake it to heart? Fye, 'tis a fault to Heauen,\nA fault against the Dead, a fault to Nature,\nTo Reason most absurd, whose common Theame\nIs death of Fathers, and who still hath cried,\nFrom the first Coarse, till he that dyed to day,\nThis must be so. We pray you throw to earth\nThis vnpreuayling woe, and thinke of vs\nAs of a Father; For let the world take note,\nYou are the most immediate to our Throne,\nAnd with no lesse Nobility of Loue,\nThen that which deerest Father beares his Sonne,\nDo I impart towards you. For your intent\nIn going backe to Schoole in Wittenberg,\nIt is most retrograde to our desire:\nAnd we beseech you, bend you to remaine\nHeere in the cheere and comfort of our eye,\nOur cheefest Courtier Cosin, and our Sonne\n\n   Qu. Let not thy Mother lose her Prayers Hamlet:\nI prythee stay with vs, go not to Wittenberg\n\n   Ham. I shall in all my best\nObey you Madam\n\n   King. Why 'tis a louing, and a faire Reply,\nBe as our selfe in Denmarke. Madam come,\nThis gentle and vnforc'd accord of Hamlet\nSits smiling to my heart; in grace whereof,\nNo iocond health that Denmarke drinkes to day,\nBut the great Cannon to the Clowds shall tell,\nAnd the Kings Rouce, the Heauens shall bruite againe,\nRespeaking earthly Thunder. Come away.\n\nExeunt.\n\nManet Hamlet.\n\n  Ham. Oh that this too too solid Flesh, would melt,\nThaw, and resolue it selfe into a Dew:\nOr that the Euerlasting had not fixt\nHis Cannon 'gainst Selfe-slaughter. O God, O God!\nHow weary, stale, flat, and vnprofitable\nSeemes to me all the vses of this world?\nFie on't? Oh fie, fie, 'tis an vnweeded Garden\nThat growes to Seed: Things rank, and grosse in Nature\nPossesse it meerely. That it should come to this:\nBut two months dead: Nay, not so much; not two,\nSo excellent a King, that was to this\nHiperion to a Satyre: so louing to my Mother,\nThat he might not beteene the windes of heauen\nVisit her face too roughly. Heauen and Earth\nMust I remember: why she would hang on him,\nAs if encrease of Appetite had growne\nBy what is fed on; and yet within a month?\nLet me not thinke on't: Frailty, thy name is woman.\nA little Month, or ere those shooes were old,\nWith which she followed my poore Fathers body\nLike Niobe, all teares. Why she, euen she.\n(O Heauen! A beast that wants discourse of Reason\nWould haue mourn'd longer) married with mine Vnkle,\nMy Fathers Brother: but no more like my Father,\nThen I to Hercules. Within a Moneth?\nEre yet the salt of most vnrighteous Teares\nHad left the flushing of her gauled eyes,\nShe married. O most wicked speed, to post\nWith such dexterity to Incestuous sheets:\nIt is not, nor it cannot come to good.\nBut breake my heart, for I must hold my tongue.\nEnter Horatio, Barnardo, and Marcellus.\n\n  Hor. Haile to your Lordship\n\n   Ham. I am glad to see you well:\nHoratio, or I do forget my selfe\n\n   Hor. The same my Lord,\nAnd your poore Seruant euer\n\n   Ham. Sir my good friend,\nIle change that name with you:\nAnd what make you from Wittenberg Horatio?\nMarcellus\n\n   Mar. My good Lord\n\n   Ham. I am very glad to see you: good euen Sir.\nBut what in faith make you from Wittemberge?\n  Hor. A truant disposition, good my Lord\n\n   Ham. I would not haue your Enemy say so;\nNor shall you doe mine eare that violence,\nTo make it truster of your owne report\nAgainst your selfe. I know you are no Truant:\nBut what is your affaire in Elsenour?\nWee'l teach you to drinke deepe, ere you depart\n\n   Hor. My Lord, I came to see your Fathers Funerall\n\n   Ham. I pray thee doe not mock me (fellow Student)\nI thinke it was to see my Mothers Wedding\n\n   Hor. Indeed my Lord, it followed hard vpon\n\n   Ham. Thrift thrift Horatio: the Funerall Bakt-meats\nDid coldly furnish forth the Marriage Tables;\nWould I had met my dearest foe in heauen,\nEre I had euer seene that day Horatio.\nMy father, me thinkes I see my father\n\n   Hor. Oh where my Lord?\n  Ham. In my minds eye (Horatio)\n  Hor. I saw him once; he was a goodly King\n\n   Ham. He was a man, take him for all in all:\nI shall not look vpon his like againe\n\n   Hor. My Lord, I thinke I saw him yesternight\n\n   Ham. Saw? Who?\n  Hor. My Lord, the King your Father\n\n   Ham. The King my Father?\n  Hor. Season your admiration for a while\nWith an attent eare; till I may deliuer\nVpon the witnesse of these Gentlemen,\nThis maruell to you\n\n   Ham. For Heauens loue let me heare\n\n   Hor. Two nights together, had these Gentlemen\n(Marcellus and Barnardo) on their Watch\nIn the dead wast and middle of the night\nBeene thus encountred. A figure like your Father,\nArm'd at all points exactly, Cap a Pe,\nAppeares before them, and with sollemne march\nGoes slow and stately: By them thrice he walkt,\nBy their opprest and feare-surprized eyes,\nWithin his Truncheons length; whilst they bestil'd\nAlmost to Ielly with the Act of feare,\nStand dumbe and speake not to him. This to me\nIn dreadfull secrecie impart they did,\nAnd I with them the third Night kept the Watch,\nWhereas they had deliuer'd both in time,\nForme of the thing; each word made true and good,\nThe Apparition comes. I knew your Father:\nThese hands are not more like\n\n   Ham. But where was this?\n  Mar. My Lord vpon the platforme where we watcht\n\n   Ham. Did you not speake to it?\n  Hor. My Lord, I did;\nBut answere made it none: yet once me thought\nIt lifted vp it head, and did addresse\nIt selfe to motion, like as it would speake:\nBut euen then, the Morning Cocke crew lowd;\nAnd at the sound it shrunke in hast away,\nAnd vanisht from our sight\n\n   Ham. Tis very strange\n\n   Hor. As I doe liue my honourd Lord 'tis true;\nAnd we did thinke it writ downe in our duty\nTo let you know of it\n\n   Ham. Indeed, indeed Sirs; but this troubles me.\nHold you the watch to Night?\n  Both. We doe my Lord\n\n   Ham. Arm'd, say you?\n  Both. Arm'd, my Lord\n\n   Ham. From top to toe?\n  Both. My Lord, from head to foote\n\n   Ham. Then saw you not his face?\n  Hor. O yes, my Lord, he wore his Beauer vp\n\n   Ham. What, lookt he frowningly?\n  Hor. A countenance more in sorrow then in anger\n\n   Ham. Pale, or red?\n  Hor. Nay very pale\n\n   Ham. And fixt his eyes vpon you?\n  Hor. Most constantly\n\n   Ham. I would I had beene there\n\n   Hor. It would haue much amaz'd you\n\n   Ham. Very like, very like: staid it long?\n  Hor. While one with moderate hast might tell a hundred\n\n   All. Longer, longer\n\n   Hor. Not when I saw't\n\n   Ham. His Beard was grisly? no\n\n   Hor. It was, as I haue seene it in his life,\nA Sable Siluer'd\n\n   Ham. Ile watch to Night; perchance 'twill wake againe\n\n   Hor. I warrant you it will\n\n   Ham. If it assume my noble Fathers person,\nIle speake to it, though Hell it selfe should gape\nAnd bid me hold my peace. I pray you all,\nIf you haue hitherto conceald this sight;\nLet it bee treble in your silence still:\nAnd whatsoeuer els shall hap to night,\nGiue it an vnderstanding but no tongue;\nI will requite your loues; so fare ye well:\nVpon the Platforme twixt eleuen and twelue,\nIle visit you\n\n   All. Our duty to your Honour.\n\nExeunt\n\n   Ham. Your loue, as mine to you: farewell.\nMy Fathers Spirit in Armes? All is not well:\nI doubt some foule play: would the Night were come;\nTill then sit still my soule; foule deeds will rise,\nThough all the earth orewhelm them to mens eies.\nEnter.\n\n\nScena Tertia\n\n\nEnter Laertes and Ophelia.\n\n  Laer. My necessaries are imbark't; Farewell:\nAnd Sister, as the Winds giue Benefit,\nAnd Conuoy is assistant; doe not sleepe,\nBut let me heare from you\n\n   Ophel. Doe you doubt that?\n  Laer. For Hamlet, and the trifling of his fauours,\nHold it a fashion and a toy in Bloude;\nA Violet in the youth of Primy Nature;\nFroward, not permanent; sweet not lasting\nThe suppliance of a minute? No more\n\n   Ophel. No more but so\n\n   Laer. Thinke it no mor

In [25]:
sents

['[The Tragedie of Hamlet by William Shakespeare 1599]\n\n\nActus Primus.',
 'Scoena Prima.',
 'Enter Barnardo and Francisco two Centinels.',
 'Barnardo.',
 "Who's there?",
 'Fran.',
 'Nay answer me: Stand & vnfold\nyour selfe\n\n   Bar.',
 'Long liue the King\n\n   Fran.',
 'Barnardo?',
 'Bar.',
 'He\n\n   Fran.',
 'You come most carefully vpon your houre\n\n   Bar.',
 "'Tis now strook twelue, get thee to bed Francisco\n\n   Fran.",
 "For this releefe much thankes: 'Tis bitter cold,\nAnd I am sicke at heart\n\n   Barn.",
 'Haue you had quiet Guard?',
 'Fran.',
 'Not a Mouse stirring\n\n   Barn.',
 'Well, goodnight.',
 'If you do meet Horatio and\nMarcellus, the Riuals of my Watch, bid them make hast.',
 'Enter Horatio and Marcellus.',
 'Fran.',
 'I thinke I heare them.',
 "Stand: who's there?",
 'Hor.',
 'Friends to this ground\n\n   Mar.',
 'And Leige-men to the Dane\n\n   Fran.',
 'Giue you good night\n\n   Mar.',
 "O farwel honest Soldier, who hath relieu'd you?",
 'Fra.',
 "Barnardo ha's my place: giue you goodnight.",
 'Exit Fran.',
 'Mar.',
 'Holla Barnardo\n\n   Bar.',
 'Say, what is Horatio there?',
 'Hor.',
 'A peece of him\n\n   Bar.',
 'Welcome Horatio, welcome good Marcellus\n\n   Mar.',
 "What, ha's this thing appear'd againe to night\n\n   Bar.",
 'I haue seene nothing\n\n   Mar.',
 "Horatio saies, 'tis but our Fantasie,\nAnd will not let beleefe take hold of him\nTouching this dreaded sight, twice seene of vs,\nTherefore I haue intreated him along\nWith vs, to watch the minutes of this Night,\nThat if againe this Apparition come,\nHe may approue our eyes, and speake to it\n\n   Hor.",
 "Tush, tush, 'twill not appeare\n\n   Bar.",
 'Sit downe a-while,\nAnd let vs once againe assaile your eares,\nThat are so fortified against our Story,\nWhat we two Nights haue seene\n\n   Hor.',
 'Well, sit we downe,\nAnd let vs heare Barnardo speake of this\n\n   Barn.',
 "Last night of all,\nWhen yond same Starre that's Westward from the Pole\nHad made his course t' illume that part of Heauen\nWhere now it burnes, Marcellus and my selfe,\nThe Bell then beating one\n\n   Mar.",
 'Peace, breake thee of:\nEnter the Ghost.',
 'Looke where it comes againe\n\n   Barn.',
 "In the same figure, like the King that's dead\n\n   Mar.",
 'Thou art a Scholler; speake to it Horatio\n\n   Barn.',
 'Lookes it not like the King?',
 'Marke it Horatio\n\n   Hora.',
 'Most like: It harrowes me with fear & wonder\n  Barn.',
 'It would be spoke too\n\n   Mar.',
 'Question it Horatio\n\n   Hor.',
 "What art thou that vsurp'st this time of night,\nTogether with that Faire and Warlike forme\nIn which the Maiesty of buried Denmarke\nDid sometimes march: By Heauen I charge thee speake\n\n   Mar.",
 'It is offended\n\n   Barn.',
 'See, it stalkes away\n\n   Hor.',
 'Stay: speake; speake: I Charge thee, speake.',
 'Exit the Ghost.',
 'Mar.',
 "'Tis gone, and will not answer\n\n   Barn.",
 'How now Horatio?',
 'You tremble & look pale:\nIs not this something more then Fantasie?',
 "What thinke you on't?",
 'Hor.',
 'Before my God, I might not this beleeue\nWithout the sensible and true auouch\nOf mine owne eyes\n\n   Mar.',
 'Is it not like the King?',
 'Hor.',
 "As thou art to thy selfe,\nSuch was the very Armour he had on,\nWhen th' Ambitious Norwey combatted:\nSo frown'd he once, when in an angry parle\nHe smot the sledded Pollax on the Ice.",
 "'Tis strange\n\n   Mar.",
 'Thus twice before, and iust at this dead houre,\nWith Martiall stalke, hath he gone by our Watch\n\n   Hor.',
 'In what particular thought to work, I know not:\nBut in the grosse and scope of my Opinion,\nThis boades some strange erruption to our State\n\n   Mar.',
 "Good now sit downe, & tell me he that knowes\nWhy this same strict and most obseruant Watch,\nSo nightly toyles the subiect of the Land,\nAnd why such dayly Cast of Brazon Cannon\nAnd Forraigne Mart for Implements of warre:\nWhy such impresse of Ship-wrights, whose sore Taske\nDo's not diuide the Sunday from the weeke,\nWhat might be toward, that this sweaty hast\nDoth make the Night ioynt-Labourer with the day:\nWho is't that can informe me?",
 'Hor.',
 "That can I,\nAt least the whisper goes so: Our last King,\nWhose Image euen but now appear'd to vs,\nWas (as you know) by Fortinbras of Norway,\n(Thereto prick'd on by a most emulate Pride)\nDar'd to the Combate.",
 "In which, our Valiant Hamlet,\n(For so this side of our knowne world esteem'd him)\nDid slay this Fortinbras: who by a Seal'd Compact,\nWell ratified by Law, and Heraldrie,\nDid forfeite (with his life) all those his Lands\nWhich he stood seiz'd on, to the Conqueror:\nAgainst the which, a Moity competent\nWas gaged by our King: which had return'd\nTo the Inheritance of Fortinbras,\nHad he bin Vanquisher, as by the same Cou'nant\nAnd carriage of the Article designe,\nHis fell to Hamlet.",
 "Now sir, young Fortinbras,\nOf vnimproued Mettle, hot and full,\nHath in the skirts of Norway, heere and there,\nShark'd vp a List of Landlesse Resolutes,\nFor Foode and Diet, to some Enterprize\nThat hath a stomacke in't: which is no other\n(And it doth well appeare vnto our State)\nBut to recouer of vs by strong hand\nAnd termes Compulsatiue, those foresaid Lands\nSo by his Father lost: and this (I take it)\nIs the maine Motiue of our Preparations,\nThe Sourse of this our Watch, and the cheefe head\nOf this post-hast, and Romage in the Land.",
 'Enter Ghost againe.',
 'But soft, behold: Loe, where it comes againe:\nIle crosse it, though it blast me.',
 'Stay Illusion:\nIf thou hast any sound, or vse of Voyce,\nSpeake to me.',
 'If there be any good thing to be done,\nThat may to thee do ease, and grace to me; speak to me.',
 'If thou art priuy to thy Countries Fate\n(Which happily foreknowing may auoyd) Oh speake.',
 'Or, if thou hast vp-hoorded in thy life\nExtorted Treasure in the wombe of Earth,\n(For which, they say, you Spirits oft walke in death)\nSpeake of it.',
 'Stay, and speake.',
 'Stop it Marcellus\n\n   Mar.',
 'Shall I strike at it with my Partizan?',
 'Hor.',
 'Do, if it will not stand\n\n   Barn.',
 "'Tis heere\n\n   Hor.",
 "'Tis heere\n\n   Mar.",
 "'Tis gone.",
 'Exit Ghost.',
 'We do it wrong, being so Maiesticall\nTo offer it the shew of Violence,\nFor it is as the Ayre, invulnerable,\nAnd our vaine blowes, malicious Mockery\n\n   Barn.',
 'It was about to speake, when the Cocke crew\n\n   Hor.',
 'And then it started, like a guilty thing\nVpon a fearfull Summons.',
 "I haue heard,\nThe Cocke that is the Trumpet to the day,\nDoth with his lofty and shrill-sounding Throate\nAwake the God of Day: and at his warning,\nWhether in Sea, or Fire, in Earth, or Ayre,\nTh' extrauagant, and erring Spirit, hyes\nTo his Confine.",
 'And of the truth heerein,\nThis present Obiect made probation\n\n   Mar.',
 'It faded on the crowing of the Cocke.',
 "Some sayes, that euer 'gainst that Season comes\nWherein our Sauiours Birch is celebrated,\nThe Bird of Dawning singeth all night long:\nAnd then (they say) no Spirit can walke abroad,\nThe nights are wholsome, then no Planets strike,\nNo Faiery talkes, nor Witch hath power to Charme:\nSo hallow'd, and so gracious is the time\n\n   Hor.",
 'So haue I heard, and do in part beleeue it.',
 "But looke, the Morne in Russet mantle clad,\nWalkes o're the dew of yon high Easterne Hill,\nBreake we our Watch vp, and by my aduice\nLet vs impart what we haue seene to night\nVnto yong Hamlet.",
 'For vpon my life,\nThis Spirit dumbe to vs, will speake to him:\nDo you consent we shall acquaint him with it,\nAs needfull in our Loues, fitting our Duty?',
 'Mar.',
 "Let do't I pray, and I this morning know\nWhere we shall finde him most conueniently.",
 'Exeunt.',
 'Scena Secunda.',
 'Enter Claudius King of Denmarke, Gertrude the Queene, Hamlet,\nPolonius,\nLaertes, and his Sister Ophelia, Lords Attendant.',
 'King.',
 'Though yet of Hamlet our deere Brothers death\nThe memory be greene: and that it vs befitted\nTo beare our hearts in greefe, and our whole Kingdome\nTo be contracted in one brow of woe:\nYet so farre hath Discretion fought with Nature,\nThat we with wisest sorrow thinke on him,\nTogether with remembrance of our selues.',
 "Therefore our sometimes Sister, now our Queene,\nTh' imperiall Ioyntresse of this warlike State,\nHaue we, as 'twere, with a defeated ioy,\nWith one Auspicious, and one Dropping eye,\nWith mirth in Funerall, and with Dirge in Marriage,\nIn equall Scale weighing Delight and Dole\nTaken to Wife; nor haue we heerein barr'd\nYour better Wisedomes, which haue freely gone\nWith this affaire along, for all our Thankes.",
 "Now followes, that you know young Fortinbras,\nHolding a weake supposall of our worth;\nOr thinking by our late deere Brothers death,\nOur State to be disioynt, and out of Frame,\nColleagued with the dreame of his Aduantage;\nHe hath not fayl'd to pester vs with Message,\nImporting the surrender of those Lands\nLost by his Father: with all Bonds of Law\nTo our most valiant Brother.",
 'So much for him.',
 'Enter Voltemand and Cornelius.',
 'Now for our selfe, and for this time of meeting\nThus much the businesse is.',
 'We haue heere writ\nTo Norway, Vncle of young Fortinbras,\nWho Impotent and Bedrid, scarsely heares\nOf this his Nephewes purpose, to suppresse\nHis further gate heerein.',
 'In that the Leuies,\nThe Lists, and full proportions are all made\nOut of his subiect: and we heere dispatch\nYou good Cornelius, and you Voltemand,\nFor bearing of this greeting to old Norway,\nGiuing to you no further personall power\nTo businesse with the King, more then the scope\nOf these dilated Articles allow:\nFarewell, and let your hast commend your duty\n\n   Volt.',
 'In that, and all things, will we shew our duty\n\n   King.',
 'We doubt it nothing, heartily farewell.',
 'Exit Voltemand and Cornelius.',
 "And now Laertes, what's the newes with you?",
 'You told vs of some suite.',
 "What is't Laertes?",
 'You cannot speake of Reason to the Dane,\nAnd loose your voyce.',
 "What would'st thou beg Laertes,\nThat shall not be my Offer, not thy Asking?",
 'The Head is not more Natiue to the Heart,\nThe Hand more instrumentall to the Mouth,\nThen is the Throne of Denmarke to thy Father.',
 "What would'st thou haue Laertes?",
 'Laer.',
 'Dread my Lord,\nYour leaue and fauour to returne to France,\nFrom whence, though willingly I came to Denmarke\nTo shew my duty in your Coronation,\nYet now I must confesse, that duty done,\nMy thoughts and wishes bend againe towards France,\nAnd bow them to your gracious leaue and pardon\n\n   King.',
 'Haue you your Fathers leaue?',
 'What sayes Pollonius?',
 'Pol.',
 'He hath my Lord:\nI do beseech you giue him leaue to go\n\n   King.',
 'Take thy faire houre Laertes, time be thine,\nAnd thy best graces spend it at thy will:\nBut now my Cosin Hamlet, and my Sonne?',
 'Ham.',
 'A little more then kin, and lesse then kinde\n\n   King.',
 'How is it that the Clouds still hang on you?',
 'Ham.',
 "Not so my Lord, I am too much i'th' Sun\n\n   Queen.",
 'Good Hamlet cast thy nightly colour off,\nAnd let thine eye looke like a Friend on Denmarke.',
 "Do not for euer with thy veyled lids\nSeeke for thy Noble Father in the dust;\nThou know'st 'tis common, all that liues must dye,\nPassing through Nature, to Eternity\n\n   Ham.",
 'I Madam, it is common\n\n   Queen.',
 'If it be;\nWhy seemes it so particular with thee\n\n   Ham.',
 'Seemes Madam?',
 "Nay, it is: I know not Seemes:\n'Tis not alone my Inky Cloake (good Mother)\nNor Customary suites of solemne Blacke,\nNor windy suspiration of forc'd breath,\nNo, nor the fruitfull Riuer in the Eye,\nNor the deiected hauiour of the Visage,\nTogether with all Formes, Moods, shewes of Griefe,\nThat can denote me truly.",
 'These indeed Seeme,\nFor they are actions that a man might play:\nBut I haue that Within, which passeth show;\nThese, but the Trappings, and the Suites of woe\n\n   King.',
 "'Tis sweet and commendable\nIn your Nature Hamlet,\nTo giue these mourning duties to your Father:\nBut you must know, your Father lost a Father,\nThat Father lost, lost his, and the Suruiuer bound\nIn filiall Obligation, for some terme\nTo do obsequious Sorrow.",
 'But to perseuer\nIn obstinate Condolement, is a course\nOf impious stubbornnesse.',
 "'Tis vnmanly greefe,\nIt shewes a will most incorrect to Heauen,\nA Heart vnfortified, a Minde impatient,\nAn Vnderstanding simple, and vnschool'd:\nFor, what we know must be, and is as common\nAs any the most vulgar thing to sence,\nWhy should we in our peeuish Opposition\nTake it to heart?",
 "Fye, 'tis a fault to Heauen,\nA fault against the Dead, a fault to Nature,\nTo Reason most absurd, whose common Theame\nIs death of Fathers, and who still hath cried,\nFrom the first Coarse, till he that dyed to day,\nThis must be so.",
 'We pray you throw to earth\nThis vnpreuayling woe, and thinke of vs\nAs of a Father; For let the world take note,\nYou are the most immediate to our Throne,\nAnd with no lesse Nobility of Loue,\nThen that which deerest Father beares his Sonne,\nDo I impart towards you.',
 'For your intent\nIn going backe to Schoole in Wittenberg,\nIt is most retrograde to our desire:\nAnd we beseech you, bend you to remaine\nHeere in the cheere and comfort of our eye,\nOur cheefest Courtier Cosin, and our Sonne\n\n   Qu.',
 'Let not thy Mother lose her Prayers Hamlet:\nI prythee stay with vs, go not to Wittenberg\n\n   Ham.',
 'I shall in all my best\nObey you Madam\n\n   King.',
 "Why 'tis a louing, and a faire Reply,\nBe as our selfe in Denmarke.",
 "Madam come,\nThis gentle and vnforc'd accord of Hamlet\nSits smiling to my heart; in grace whereof,\nNo iocond health that Denmarke drinkes to day,\nBut the great Cannon to the Clowds shall tell,\nAnd the Kings Rouce, the Heauens shall bruite againe,\nRespeaking earthly Thunder.",
 'Come away.',
 'Exeunt.',
 'Manet Hamlet.',
 'Ham.',
 "Oh that this too too solid Flesh, would melt,\nThaw, and resolue it selfe into a Dew:\nOr that the Euerlasting had not fixt\nHis Cannon 'gainst Selfe-slaughter.",
 'O God, O God!',
 'How weary, stale, flat, and vnprofitable\nSeemes to me all the vses of this world?',
 "Fie on't?",
 "Oh fie, fie, 'tis an vnweeded Garden\nThat growes to Seed: Things rank, and grosse in Nature\nPossesse it meerely.",
 'That it should come to this:\nBut two months dead: Nay, not so much; not two,\nSo excellent a King, that was to this\nHiperion to a Satyre: so louing to my Mother,\nThat he might not beteene the windes of heauen\nVisit her face too roughly.',
 'Heauen and Earth\nMust I remember: why she would hang on him,\nAs if encrease of Appetite had growne\nBy what is fed on; and yet within a month?',
 "Let me not thinke on't: Frailty, thy name is woman.",
 'A little Month, or ere those shooes were old,\nWith which she followed my poore Fathers body\nLike Niobe, all teares.',
 'Why she, euen she.',
 '(O Heauen!',
 "A beast that wants discourse of Reason\nWould haue mourn'd longer) married with mine Vnkle,\nMy Fathers Brother: but no more like my Father,\nThen I to Hercules.",
 'Within a Moneth?',
 'Ere yet the salt of most vnrighteous Teares\nHad left the flushing of her gauled eyes,\nShe married.',
 'O most wicked speed, to post\nWith such dexterity to Incestuous sheets:\nIt is not, nor it cannot come to good.',
 'But breake my heart, for I must hold my tongue.',
 'Enter Horatio, Barnardo, and Marcellus.',
 'Hor.',
 'Haile to your Lordship\n\n   Ham.',
 'I am glad to see you well:\nHoratio, or I do forget my selfe\n\n   Hor.',
 'The same my Lord,\nAnd your poore Seruant euer\n\n   Ham.',
 'Sir my good friend,\nIle change that name with you:\nAnd what make you from Wittenberg Horatio?',
 'Marcellus\n\n   Mar.',
 'My good Lord\n\n   Ham.',
 'I am very glad to see you: good euen Sir.',
 'But what in faith make you from Wittemberge?',
 'Hor.',
 'A truant disposition, good my Lord\n\n   Ham.',
 'I would not haue your Enemy say so;\nNor shall you doe mine eare that violence,\nTo make it truster of your owne report\nAgainst your selfe.',
 'I know you are no Truant:\nBut what is your affaire in Elsenour?',
 "Wee'l teach you to drinke deepe, ere you depart\n\n   Hor.",
 'My Lord, I came to see your Fathers Funerall\n\n   Ham.',
 'I pray thee doe not mock me (fellow Student)\nI thinke it was to see my Mothers Wedding\n\n   Hor.',
 'Indeed my Lord, it followed hard vpon\n\n   Ham.',
 'Thrift thrift Horatio: the Funerall Bakt-meats\nDid coldly furnish forth the Marriage Tables;\nWould I had met my dearest foe in heauen,\nEre I had euer seene that day Horatio.',
 'My father, me thinkes I see my father\n\n   Hor.',
 'Oh where my Lord?',
 'Ham.',
 'In my minds eye (Horatio)\n  Hor.',
 'I saw him once; he was a goodly King\n\n   Ham.',
 'He was a man, take him for all in all:\nI shall not look vpon his like againe\n\n   Hor.',
 'My Lord, I thinke I saw him yesternight\n\n   Ham.',
 'Saw?',
 'Who?',
 'Hor.',
 'My Lord, the King your Father\n\n   Ham.',
 'The King my Father?',
 'Hor.',
 'Season your admiration for a while\nWith an attent eare; till I may deliuer\nVpon the witnesse of these Gentlemen,\nThis maruell to you\n\n   Ham.',
 'For Heauens loue let me heare\n\n   Hor.',
 'Two nights together, had these Gentlemen\n(Marcellus and Barnardo) on their Watch\nIn the dead wast and middle of the night\nBeene thus encountred.',
 "A figure like your Father,\nArm'd at all points exactly, Cap a Pe,\nAppeares before them, and with sollemne march\nGoes slow and stately: By them thrice he walkt,\nBy their opprest and feare-surprized eyes,\nWithin his Truncheons length; whilst they bestil'd\nAlmost to Ielly with the Act of feare,\nStand dumbe and speake not to him.",
 "This to me\nIn dreadfull secrecie impart they did,\nAnd I with them the third Night kept the Watch,\nWhereas they had deliuer'd both in time,\nForme of the thing; each word made true and good,\nThe Apparition comes.",
 'I knew your Father:\nThese hands are not more like\n\n   Ham.',
 'But where was this?',
 'Mar.',
 'My Lord vpon the platforme where we watcht\n\n   Ham.',
 'Did you not speake to it?',
 'Hor.',
 'My Lord, I did;\nBut answere made it none: yet once me thought\nIt lifted vp it head, and did addresse\nIt selfe to motion, like as it would speake:\nBut euen then, the Morning Cocke crew lowd;\nAnd at the sound it shrunke in hast away,\nAnd vanisht from our sight\n\n   Ham.',
 'Tis very strange\n\n   Hor.',
 "As I doe liue my honourd Lord 'tis true;\nAnd we did thinke it writ downe in our duty\nTo let you know of it\n\n   Ham.",
 'Indeed, indeed Sirs; but this troubles me.',
 'Hold you the watch to Night?',
 'Both.',
 'We doe my Lord\n\n   Ham.',
 "Arm'd, say you?",
 'Both.',
 "Arm'd, my Lord\n\n   Ham.",
 'From top to toe?',
 'Both.',
 'My Lord, from head to foote\n\n   Ham.',
 'Then saw you not his face?',
 'Hor.',
 'O yes, my Lord, he wore his Beauer vp\n\n   Ham.',
 'What, lookt he frowningly?',
 'Hor.',
 'A countenance more in sorrow then in anger\n\n   Ham.',
 'Pale, or red?',
 'Hor.',
 'Nay very pale\n\n   Ham.',
 'And fixt his eyes vpon you?',
 'Hor.',
 'Most constantly\n\n   Ham.',
 'I would I had beene there\n\n   Hor.',
 "It would haue much amaz'd you\n\n   Ham.",
 'Very like, very like: staid it long?',
 'Hor.',
 'While one with moderate hast might tell a hundred\n\n   All.',
 'Longer, longer\n\n   Hor.',
 "Not when I saw't\n\n   Ham.",
 'His Beard was grisly?',
 'no\n\n   Hor.',
 "It was, as I haue seene it in his life,\nA Sable Siluer'd\n\n   Ham.",
 "Ile watch to Night; perchance 'twill wake againe\n\n   Hor.",
 'I warrant you it will\n\n   Ham.',
 'If it assume my noble Fathers person,\nIle speake to it, though Hell it selfe should gape\nAnd bid me hold my peace.',

In [28]:
tfidf_vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function my_tokenizer at 0x7ffb68e3b9d8>, use_idf=True,
        vocabulary=None)

In [29]:
print([k for k in tfidf_vectorizer.vocabulary_.keys()][:20])

['tragedie', 'hamlet', 'william', 'shakespeare', '1599', 'actus', 'primus', 'scoena', 'prima', 'enter', 'barnardo', 'francisco', 'two', 'centinels', "'s", 'fran', 'nay', 'answer', 'stand', 'vnfold']

In [30]:
print(tfs[:50,:50])#linha 0 coluna 17

  (0, 17)	0.4098405429500896
  (4, 5)	1.0
  (12, 6)	0.25569565102708125
  (13, 6)	0.24183188573710981
  (22, 5)	0.5865767987601467
  (27, 0)	0.226773205328385
  (29, 5)	0.28458175550618814
  (37, 5)	0.26402019659267234
  (37, 0)	0.23602778459784524
  (39, 6)	0.13875455587670743
  (40, 13)	0.35297267044370917
  (41, 25)	0.31475626155215114
  (43, 5)	0.14416024946136125
  (46, 5)	0.32299630350190056