In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [4]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)
base.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [ ]:
base.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,221900.0,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,538000.0,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,180000.0,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,604000.0,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,510000.0,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [ ]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])
base.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,0.019266,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,0.060721,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,0.013770,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,0.069377,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,0.057049,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [ ]:
X = base.drop('price', axis = 1)
y = base.price

In [ ]:
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [ ]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [ ]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [ ]:
import tensorflow as tf

In [ ]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [ ]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [ ]:
X_treinamento.shape

(15129, 16)

In [ ]:
X_teste.shape

(6484, 16)

In [ ]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento, batch_size = 32,
                                                        num_epochs = None, shuffle = True)
regressor = tf.estimator.DNNRegressor(hidden_units = [8, 8, 8], feature_columns=colunas)
regressor.train(input_fn = funcao_treinamento, steps = 20000)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\183134\AppData\Local\Temp\tmpwda41xqy
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\183134\\AppData\\Local\\Temp\\tmpwda41xqy', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000231358852B0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From C:\Users\183134\AppData\Local\conda\conda\envs\TensorFlow\lib\site-packages\tensorflow\python\training\monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\183134\AppData\Local\Temp\tmpwda41xqy\model.ckpt.
INFO:tensorflow:loss = 0.06229514, step = 1
INFO:tensorflow:global_step/sec: 196.938
INFO:tensorflow:loss = 0.04614692, step = 101 (0.534 sec)
INFO:tensorflow:global_step/sec: 187.704
INFO:tensorflow:loss = 0.024474226, step = 201 (0.528 sec)
INFO:tensorflow:global_step/sec: 199.831
INFO:tensorflow:loss = 0.020043895, step = 301 (0.523 sec)
INFO:tensorflow:global_step/sec: 182.015
INFO:tensorflow:loss = 0.024346564, step = 401 (0.517 sec)
INFO:tensorflow:global_step/sec: 200.097
INFO:tensorflow:loss = 0.019350307, step = 501 (0.514 sec)
INFO:tensorflow:global_step/sec: 193.554
INFO:tensorflow:loss = 0.029141895, step = 601 (0.509 sec)
INFO:tensorflow:global_step/sec: 178.849
INFO:tensorflow:loss = 0.012144702, step = 701 (0.556 sec)
INFO:tensorflow:global_step/sec: 184.657
INFO:tensorflow:loss = 0.022932373, step = 801 (0.598 sec)
INFO:tensorflow:global_step/sec: 120.21
INFO:tensorflow:loss = 0.0058578714, step = 901 (0.761 sec)
INFO:tensorflow:global_step/sec: 180.857
INFO:tensorflow:loss = 0.0072035296, step = 1001 (0.564 sec)
INFO:tensorflow:global_step/sec: 194.843
INFO:tensorflow:loss = 0.009560238, step = 1101 (0.511 sec)
INFO:tensorflow:global_step/sec: 194.549
INFO:tensorflow:loss = 0.016789412, step = 1201 (0.511 sec)
INFO:tensorflow:global_step/sec: 204.001
INFO:tensorflow:loss = 0.02462092, step = 1301 (0.508 sec)
INFO:tensorflow:global_step/sec: 218.663
INFO:tensorflow:loss = 0.01278265, step = 1401 (0.448 sec)
INFO:tensorflow:global_step/sec: 222.522
INFO:tensorflow:loss = 0.04015094, step = 1501 (0.461 sec)
INFO:tensorflow:global_step/sec: 220.259
INFO:tensorflow:loss = 0.0097088665, step = 1601 (0.427 sec)
INFO:tensorflow:global_step/sec: 217.968
INFO:tensorflow:loss = 0.013375468, step = 1701 (0.485 sec)
INFO:tensorflow:global_step/sec: 221.898
INFO:tensorflow:loss = 0.027831886, step = 1801 (0.441 sec)
INFO:tensorflow:global_step/sec: 233.98
INFO:tensorflow:loss = 0.025073506, step = 1901 (0.426 sec)
INFO:tensorflow:global_step/sec: 225.501
INFO:tensorflow:loss = 0.0063765696, step = 2001 (0.446 sec)
INFO:tensorflow:global_step/sec: 214.522
INFO:tensorflow:loss = 0.0094913365, step = 2101 (0.448 sec)
INFO:tensorflow:global_step/sec: 221.911
INFO:tensorflow:loss = 0.009747836, step = 2201 (0.464 sec)
INFO:tensorflow:global_step/sec: 230.299
INFO:tensorflow:loss = 0.029300693, step = 2301 (0.446 sec)
INFO:tensorflow:global_step/sec: 226.599
INFO:tensorflow:loss = 0.01897265, step = 2401 (0.441 sec)
INFO:tensorflow:global_step/sec: 132.554
INFO:tensorflow:loss = 0.009722753, step = 2501 (0.739 sec)
INFO:tensorflow:global_step/sec: 162.681
INFO:tensorflow:loss = 0.015854273, step = 2601 (0.614 sec)
INFO:tensorflow:global_step/sec: 159.53
INFO:tensorflow:loss = 0.009301542, step = 2701 (0.629 sec)
INFO:tensorflow:global_step/sec: 217.775
INFO:tensorflow:loss = 0.008501533, step = 2801 (0.462 sec)
INFO:tensorflow:global_step/sec: 211.552
INFO:tensorflow:loss = 0.017788218, step = 2901 (0.476 sec)
INFO:tensorflow:global_step/sec: 226.129
INFO:tensorflow:loss = 0.02726318, step = 3001 (0.441 sec)
INFO:tensorflow:global_step/sec: 189.027
INFO:tensorflow:loss = 0.014697973, step = 3101 (0.533 sec)
INFO:tensorflow:global_step/sec: 192.356
INFO:tensorflow:loss = 0.01066752, step = 3201 (0.526 sec)
INFO:tensorflow:global_step/sec: 178.189
INFO:tensorflow:loss = 0.02684238, step = 3301 (0.586 sec)
INFO:tensorflow:global_step/sec: 191.526
INFO:tensorflow:loss = 0.009836892, step = 3401 (0.487 sec)
INFO:tensorflow:global_step/sec: 186.985
INFO:tensorflow:loss = 0.012395921, step = 3501 (0.540 sec)
INFO:tensorflow:global_step/sec: 194.99
INFO:tensorflow:loss = 0.012962835, step = 3601 (0.508 sec)
INFO:tensorflow:global_step/sec: 177.864
INFO:tensorflow:loss = 0.024347892, step = 3701 (0.559 sec)
INFO:tensorflow:global_step/sec: 197.034
INFO:tensorflow:loss = 0.006153741, step = 3801 (0.511 sec)
INFO:tensorflow:global_step/sec: 177.838
INFO:tensorflow:loss = 0.06646178, step = 3901 (0.560 sec)
INFO:tensorflow:global_step/sec: 182.474
INFO:tensorflow:loss = 0.0066812905, step = 4001 (0.551 sec)
INFO:tensorflow:global_step/sec: 189.101
INFO:tensorflow:loss = 0.00880061, step = 4101 (0.521 sec)
INFO:tensorflow:global_step/sec: 185.181
INFO:tensorflow:loss = 0.021526149, step = 4201 (0.541 sec)
INFO:tensorflow:global_step/sec: 197.234
INFO:tensorflow:loss = 0.0132065425, step = 4301 (0.507 sec)
INFO:tensorflow:global_step/sec: 184.498
INFO:tensorflow:loss = 0.013096504, step = 4401 (0.545 sec)
INFO:tensorflow:global_step/sec: 209.828
INFO:tensorflow:loss = 0.0060078404, step = 4501 (0.484 sec)
INFO:tensorflow:global_step/sec: 214.417
INFO:tensorflow:loss = 0.015297735, step = 4601 (0.457 sec)
INFO:tensorflow:global_step/sec: 232.806
INFO:tensorflow:loss = 0.041213766, step = 4701 (0.434 sec)
INFO:tensorflow:global_step/sec: 232.453
INFO:tensorflow:loss = 0.0074735107, step = 4801 (0.438 sec)
INFO:tensorflow:global_step/sec: 217.673
INFO:tensorflow:loss = 0.015265796, step = 4901 (0.454 sec)
INFO:tensorflow:global_step/sec: 228.46
INFO:tensorflow:loss = 0.0033841105, step = 5001 (0.444 sec)
INFO:tensorflow:global_step/sec: 221.489
INFO:tensorflow:loss = 0.011693549, step = 5101 (0.450 sec)
INFO:tensorflow:global_step/sec: 223.722
INFO:tensorflow:loss = 0.010829538, step = 5201 (0.438 sec)
INFO:tensorflow:global_step/sec: 227.688
INFO:tensorflow:loss = 0.0062605916, step = 5301 (0.447 sec)
INFO:tensorflow:global_step/sec: 221.576
INFO:tensorflow:loss = 0.041109823, step = 5401 (0.443 sec)
INFO:tensorflow:global_step/sec: 230.377
INFO:tensorflow:loss = 0.019956276, step = 5501 (0.444 sec)
INFO:tensorflow:global_step/sec: 222.506
INFO:tensorflow:loss = 0.013662697, step = 5601 (0.446 sec)
INFO:tensorflow:global_step/sec: 223.961

INFO:tensorflow:loss = 0.015431197, step = 5701 (0.438 sec)
INFO:tensorflow:global_step/sec: 226.233
INFO:tensorflow:loss = 0.01166264, step = 5801 (0.447 sec)
INFO:tensorflow:global_step/sec: 221.97
INFO:tensorflow:loss = 0.015911875, step = 5901 (0.461 sec)
INFO:tensorflow:global_step/sec: 218.448
INFO:tensorflow:loss = 0.0464836, step = 6001 (0.444 sec)
INFO:tensorflow:global_step/sec: 231.762
INFO:tensorflow:loss = 0.02483767, step = 6101 (0.433 sec)
INFO:tensorflow:global_step/sec: 229.939
INFO:tensorflow:loss = 0.009436805, step = 6201 (0.433 sec)
INFO:tensorflow:global_step/sec: 227.838
INFO:tensorflow:loss = 0.011365178, step = 6301 (0.440 sec)
INFO:tensorflow:global_step/sec: 204.151
INFO:tensorflow:loss = 0.009065448, step = 6401 (0.494 sec)
INFO:tensorflow:global_step/sec: 199.869
INFO:tensorflow:loss = 0.018140422, step = 6501 (0.508 sec)
INFO:tensorflow:global_step/sec: 194.14
INFO:tensorflow:loss = 0.010772336, step = 6601 (0.501 sec)
INFO:tensorflow:global_step/sec: 188.175
INFO:tensorflow:loss = 0.028364906, step = 6701 (0.535 sec)
INFO:tensorflow:global_step/sec: 192.944
INFO:tensorflow:loss = 0.008180052, step = 6801 (0.504 sec)
INFO:tensorflow:global_step/sec: 205.889
INFO:tensorflow:loss = 0.020244751, step = 6901 (0.505 sec)
INFO:tensorflow:global_step/sec: 188.579
INFO:tensorflow:loss = 0.02024695, step = 7001 (0.534 sec)
INFO:tensorflow:global_step/sec: 199.192
INFO:tensorflow:loss = 0.02612054, step = 7101 (0.501 sec)
INFO:tensorflow:global_step/sec: 193.985
INFO:tensorflow:loss = 0.0069141816, step = 7201 (0.509 sec)
INFO:tensorflow:global_step/sec: 199.039
INFO:tensorflow:loss = 0.012088339, step = 7301 (0.535 sec)
INFO:tensorflow:global_step/sec: 174.979
INFO:tensorflow:loss = 0.010261608, step = 7401 (0.535 sec)
INFO:tensorflow:global_step/sec: 209.201
INFO:tensorflow:loss = 0.014213452, step = 7501 (0.476 sec)
INFO:tensorflow:global_step/sec: 191.567
INFO:tensorflow:loss = 0.0065784296, step = 7601 (0.526 sec)
INFO:tensorflow:global_step/sec: 202.053
INFO:tensorflow:loss = 0.00860971, step = 7701 (0.503 sec)
INFO:tensorflow:global_step/sec: 213.972
INFO:tensorflow:loss = 0.045730248, step = 7801 (0.445 sec)
INFO:tensorflow:global_step/sec: 226.336
INFO:tensorflow:loss = 0.012931392, step = 7901 (0.454 sec)
INFO:tensorflow:global_step/sec: 230.084
INFO:tensorflow:loss = 0.009808389, step = 8001 (0.439 sec)
INFO:tensorflow:global_step/sec: 225.639
INFO:tensorflow:loss = 0.013669854, step = 8101 (0.440 sec)
INFO:tensorflow:global_step/sec: 223.348
INFO:tensorflow:loss = 0.0123669235, step = 8201 (0.452 sec)
INFO:tensorflow:global_step/sec: 225.643
INFO:tensorflow:loss = 0.008968642, step = 8301 (0.425 sec)
INFO:tensorflow:global_step/sec: 232.294
INFO:tensorflow:loss = 0.0102831395, step = 8401 (0.455 sec)
INFO:tensorflow:global_step/sec: 221.55
INFO:tensorflow:loss = 0.009936029, step = 8501 (0.445 sec)
INFO:tensorflow:global_step/sec: 227.635
INFO:tensorflow:loss = 0.010639207, step = 8601 (0.438 sec)
INFO:tensorflow:global_step/sec: 185.012
INFO:tensorflow:loss = 0.006560092, step = 8701 (0.536 sec)
INFO:tensorflow:global_step/sec: 161.463
INFO:tensorflow:loss = 0.0103872735, step = 8801 (0.617 sec)
INFO:tensorflow:global_step/sec: 136.43
INFO:tensorflow:loss = 0.012824997, step = 8901 (0.744 sec)
INFO:tensorflow:global_step/sec: 174.387
INFO:tensorflow:loss = 0.022063125, step = 9001 (0.569 sec)
INFO:tensorflow:global_step/sec: 130.008
INFO:tensorflow:loss = 0.0045190062, step = 9101 (0.774 sec)
INFO:tensorflow:global_step/sec: 223.807
INFO:tensorflow:loss = 0.0020004804, step = 9201 (0.438 sec)
INFO:tensorflow:global_step/sec: 225.166
INFO:tensorflow:loss = 0.006818438, step = 9301 (0.443 sec)
INFO:tensorflow:global_step/sec: 235.46
INFO:tensorflow:loss = 0.009588406, step = 9401 (0.434 sec)
INFO:tensorflow:global_step/sec: 221.544
INFO:tensorflow:loss = 0.009142557, step = 9501 (0.451 sec)
INFO:tensorflow:global_step/sec: 196.949
INFO:tensorflow:loss = 0.009261159, step = 9601 (0.515 sec)
INFO:tensorflow:global_step/sec: 194.815
INFO:tensorflow:loss = 0.003967484, step = 9701 (0.506 sec)
INFO:tensorflow:global_step/sec: 196.629
INFO:tensorflow:loss = 0.0150426105, step = 9801 (0.503 sec)
INFO:tensorflow:global_step/sec: 194.009
INFO:tensorflow:loss = 0.018055556, step = 9901 (0.514 sec)
INFO:tensorflow:global_step/sec: 205.796
INFO:tensorflow:loss = 0.009639373, step = 10001 (0.486 sec)
INFO:tensorflow:global_step/sec: 199.609
INFO:tensorflow:loss = 0.017438065, step = 10101 (0.502 sec)
INFO:tensorflow:global_step/sec: 185.339
INFO:tensorflow:loss = 0.0072114654, step = 10201 (0.541 sec)
INFO:tensorflow:global_step/sec: 181.967
INFO:tensorflow:loss = 0.0059790057, step = 10301 (0.554 sec)
INFO:tensorflow:global_step/sec: 164.042
INFO:tensorflow:loss = 0.011717845, step = 10401 (0.589 sec)

In [ ]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)
previsoes = regressor.predict(input_fn=funcao_previsao)
list(previsoes)

In [ ]:
valores_previsao = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsao.append(p['predictions'][0])

In [ ]:
valores_previsao

In [ ]:
import numpy as np
valores_previsao = np.asarray(valores_previsao).reshape(-1,1)
valores_previsao = scaler_y.inverse_transform(valores_previsao)
valores_previsao

In [ ]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2 = scaler_y.inverse_transform(y_teste2)
y_teste2

In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsao)
mae