# RMS Titanic

## O RMS Titanic foi um navio de passageiros britânico operado pela White Star Line e construído pelos estaleiros da Harland and Wolff em Belfast. Foi a segunda embarcação da Classe Olympic de transatlânticos depois do RMS Olympic e seguido pelo HMHS Britannic. Projetado pelos engenheiros navais Alexander Carlisle e Thomas Andrews, sua construção começou em março de 1909 e ele foi lançado ao mar em maio de 1911. O Titanic foi pensado para ser o navio mais luxuoso e mais seguro de sua época, gerando lendas que era supostamente "inafundável".

## A embarcação partiu em sua viagem inaugural de Southampton para Nova Iorque em 10 de abril de 1912, no caminho passando em Cherbourg-Octeville na França e por Queenstown na Irlanda. Ele colidiu com um iceberg às 23h40min do dia 14 de abril e afundou na madrugada do dia seguinte matando mais de 1500 pessoas, sendo um dos maiores desastres marítimos em tempos de paz de toda a história. Seu naufrágio destacou vários pontos fracos de seu projeto, deficiências nos procedimentos de evacuação de emergência e falhas nas regulamentações marítimas da época. Comissões de inquérito foram instauradas nos Estados Unidos e no Reino Unido, levando a mudanças nas leis internacionais de navegação que permanecem em vigor mais de um século depois.

## Os destroços do Titanic foram procurados por décadas até serem encontrados em 1985 por uma equipe liderada por Robert Ballard. Ele se encontra a 3843 m de profundidade e a 650 km ao sudeste de Terra Nova no Canadá. Sua história e naufrágio permaneceram no imaginário popular durante décadas, levando a produção de vários livros e filmes a seu respeito, mais notavelmente o filme Titanic de 1997. Até hoje o Titanic permanece como um dos navios mais famosos da história, com seus destroços atraindo várias expedições de exploração ao longo dos anos.

*Fonte:* [WikiPedia](https://pt.wikipedia.org/wiki/RMS_Titanic)

--------

## A equipa da [Udacity](https://udacity.com) disponibilizou informações sobre uma parte dos passageiros à bordo do RMS Titanic no dia daquela tragédia. Esse _dataset_ que contém informações reais vem sendo utilizado em diversos estudos de caso, além de servir de base para aprendizado de Ciência de Dados, Estatística e Machine Learning.

## O arquivo **titanic_data.csv** contém informações reais sobre os passageiros organizadas da seguinte forma:

- Survived (Sobreviveu): 0 = Não, 1 = Sim
- Pclass (Classe): Classe de ingresso 1 = 1º, 2 = 2º, 3 = 3º
- Sex (Sexo): Sexo do passageiro
- Age (Idade): Idade em anos
- Sibsp: Quantidade de irmãos / cônjuges a bordo do Titanic
- Parch: Quantidade de pais / crianças a bordo do Titanic
- Ticket (Bilhete): Número do bilhete de embarque
- Fare (Tarifa): Tarifa paga pelo Passageiro
- Cabin (Cabine): Número de cabine
- Embarked (Embarque): Porto de Embarque (C = Cherbourg, Q = Queenstown, S = Southampton)

## O objetivo deste estudo é obter algumas informações estatísticas sobre a tragédia e realizar alguns _insights_ a respeito dos tripulantes e das circunstâncias do acidente.

## Efetue a carga do arquivo através da biblioteca _Pandas_ e a partir do _DataFrame_ gerado, efetue as operações necessárias para responder as questões.

## Importando o DataSet

### 1 - Efetuar a leitura do dataset através do Pandas, gerando um DataFrame de nome tit, levando-se em consideração que o arquivo encontra-se na mesma pasta do notebook.

In [31]:
import pandas as pd
import numpy as np

In [32]:
desired_width = 320
pd.set_option('display.width', desired_width)
np.set_printoptions(linewidth=desired_width)
pd.set_option('display.max_columns',20)
pd.set_option('display.max_rows', None)

In [33]:
tit = pd.read_csv('titanic_data.csv',delimiter=',',encoding='utf-8')
tit.head()

   PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
4            5         0       3                           Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S

## Conhecendo o DataSet

### 2 - Quantas linhas e colunas tem o dataset? Quais os tipos das colunas?

In [34]:
# linhas
tit['Name'].count()

891

In [35]:
# colunas
len(tit.columns)

12

In [36]:
tit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

### 3 - Mostre os dados dos dez primeiros e 8 últimos registros do dataset.

In [37]:
pd.concat([tit.head(10),tit.iloc[-8:]])

     PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2              3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
4              5         0       3                           Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S
5              6         0       3                                   Moran, Mr. James    male   NaN      0      0            330877   8.4583   NaN        Q
6              7         0       1                            McCarthy, Mr. Timothy J    male  54.0      0      0             17463  51.8625   E46        S
7              8         0       3                     Palsson, Master. Gosta Leonard    male   2.0      3      1            349909  21.0750   NaN        S
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0      2            347742  11.1333   NaN        S
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1      0            237736  30.0708   NaN        C
883          884         0       2                      Banfield, Mr. Frederick James    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884          885         0       3                             Sutehall, Mr. Henry Jr    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
885          886         0       3               Rice, Mrs. William (Margaret Norton)  female  39.0      0      5            382652  29.1250   NaN        Q
886          887         0       2                              Montvila, Rev. Juozas    male  27.0      0      0            211536  13.0000   NaN        S
887          888         1       1                       Graham, Miss. Margaret Edith  female  19.0      0      0            112053  30.0000   B42        S
888          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889          890         1       1                              Behr, Mr. Karl Howell    male  26.0      0      0            111369  30.0000  C148        C
890          891         0       3                                Dooley, Mr. Patrick    male  32.0      0      0            370376   7.7500   NaN        Q

### 4 - Cálculos envolvendo colunas numéricas com dados faltantes podem sofrer impacto. É possível afirmar se há dados faltantes no dataset? Caso positivo, quais e quantos seriam esses dados? Preencha os dados faltantes de forma que não influenciem em operações futuras.

In [56]:
z = tit.isnull().any() #verificar nan
x = tit.columns[z] #where is nan
tit[x].isnull().sum() #how many nan
tit.dropna(subset=['Idade'])

     IdPassageiro Sobreviveu  Classe                                               Nome    Sexo  Idade    Tarifa           Cabine Embarque
0               1        Não       3                            Braund, Mr. Owen Harris   Homem  22.00    7.2500              NaN        S
1               2        Sim       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  Mulher  38.00   71.2833              C85        C
2               3        Sim       3                             Heikkinen, Miss. Laina  Mulher  26.00    7.9250              NaN        S
3               4        Sim       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  Mulher  35.00   53.1000             C123        S
4               5        Não       3                           Allen, Mr. William Henry   Homem  35.00    8.0500              NaN        S
6               7        Não       1                            McCarthy, Mr. Timothy J   Homem  54.00   51.8625              E46        S
7               8        Não       3                     Palsson, Master. Gosta Leonard   Homem   2.00   21.0750              NaN        S
8               9        Sim       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  Mulher  27.00   11.1333              NaN        S
9              10        Sim       2                Nasser, Mrs. Nicholas (Adele Achem)  Mulher  14.00   30.0708              NaN        C
10             11        Sim       3                    Sandstrom, Miss. Marguerite Rut  Mulher   4.00   16.7000               G6        S
11             12        Sim       1                           Bonnell, Miss. Elizabeth  Mulher  58.00   26.5500             C103        S
12             13        Não       3                     Saundercock, Mr. William Henry   Homem  20.00    8.0500              NaN        S
13             14        Não       3                        Andersson, Mr. Anders Johan   Homem  39.00   31.2750              NaN        S
14             15        Não       3               Vestrom, Miss. Hulda Amanda Adolfina  Mulher  14.00    7.8542              NaN        S
15             16        Sim       2                   Hewlett, Mrs. (Mary D Kingcome)   Mulher  55.00   16.0000              NaN        S
16             17        Não       3                               Rice, Master. Eugene   Homem   2.00   29.1250              NaN        Q
18             19        Não       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  Mulher  31.00   18.0000              NaN        S
20             21        Não       2                               Fynney, Mr. Joseph J   Homem  35.00   26.0000              NaN        S
21             22        Sim       2                              Beesley, Mr. Lawrence   Homem  34.00   13.0000              D56        S
22             23        Sim       3                        McGowan, Miss. Anna "Annie"  Mulher  15.00    8.0292              NaN        Q
23             24        Sim       1                       Sloper, Mr. William Thompson   Homem  28.00   35.5000               A6        S
24             25        Não       3                      Palsson, Miss. Torborg Danira  Mulher   8.00   21.0750              NaN        S
25             26        Sim       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  Mulher  38.00   31.3875              NaN        S
27             28        Não       1                     Fortune, Mr. Charles Alexander   Homem  19.00  263.0000      C23 C25 C27        S
30             31        Não       1                           Uruchurtu, Don. Manuel E   Homem  40.00   27.7208              NaN        C
33             34        Não       2                              Wheadon, Mr. Edward H   Homem  66.00   10.5000              NaN        S
34             35        Não       1                            Meyer, Mr. Edgar Joseph   Homem  28.00   82.1708              NaN        C
35             36        Não       1                     Holverson, Mr. Alexander Oskar   Homem  42.00   52.0000              NaN        S
37             38        Não       3                           Cann, Mr. Ernest Charles   Homem  21.00    8.0500              NaN        S
38             39        Não       3                 Vander Planke, Miss. Augusta Maria  Mulher  18.00   18.0000              NaN        S
39             40        Sim       3                        Nicola-Yarred, Miss. Jamila  Mulher  14.00   11.2417              NaN        C
40             41        Não       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  Mulher  40.00    9.4750              NaN        S
41             42        Não       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  Mulher  27.00   21.0000              NaN        S
43             44        Sim       2           Laroche, Miss. Simonne Marie Anne Andree  Mulher   3.00   41.5792              NaN        C
44             45        Sim       3                      Devaney, Miss. Margaret Delia  Mulher  19.00    7.8792              NaN        Q
49             50        Não       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  Mulher  18.00   17.8000              NaN        S
50             51        Não       3                         Panula, Master. Juha Niilo   Homem   7.00   39.6875              NaN        S
51             52        Não       3                       Nosworthy, Mr. Richard Cater   Homem  21.00    7.8000              NaN        S
52             53        Sim       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  Mulher  49.00   76.7292              D33        C
53             54        Sim       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  Mulher  29.00   26.0000              NaN        S
54             55        Não       1                     Ostby, Mr. Engelhart Cornelius   Homem  65.00   61.9792              B30        C
56             57        Sim       2                                  Rugg, Miss. Emily  Mulher  21.00   10.5000              NaN        S
57             58        Não       3                                Novel, Mr. Mansouer   Homem  28.50    7.2292              NaN        C
58             59        Sim       2                       West, Miss. Constance Mirium  Mulher   5.00   27.7500              NaN        S
59             60        Não       3                 Goodwin, Master. William Frederick   Homem  11.00   46.9000              NaN        S
60             61        Não       3                              Sirayanian, Mr. Orsen   Homem  22.00    7.2292              NaN        C
61             62        Sim       1                                Icard, Miss. Amelie  Mulher  38.00   80.0000              B28      NaN
62             63        Não       1                        Harris, Mr. Henry Birkhardt   Homem  45.00   83.4750              C83        S
63             64        Não       3                              Skoog, Master. Harald   Homem   4.00   27.9000              NaN        S
66             67        Sim       2                       Nye, Mrs. (Elizabeth Ramell)  Mulher  29.00   10.5000              F33        S
67             68        Não       3                           Crease, Mr. Ernest James   Homem  19.00    8.1583              NaN        S
68             69        Sim       3                    Andersson, Miss. Erna Alexandra  Mulher  17.00    7.9250              NaN        S
69             70        Não       3                                  Kink, Mr. Vincenz   Homem  26.00    8.6625              NaN        S
70             71        Não       2                         Jenkin, Mr. Stephen Curnow   Homem  32.00   10.5000              NaN        S
71             72        Não       3                         Goodwin, Miss. Lillian Amy  Mulher  16.00   46.9000              NaN        S
72             73        Não       2                               Hood, Mr. Ambrose Jr   Homem  21.00   73.5000              NaN        S
73             74        Não       3                        Chronopoulos, Mr. Apostolos   Homem  26.00   14.4542              NaN        C
74             75        Sim       3                                      Bing, Mr. Lee   Homem  32.00   56.4958              NaN        S
75             76        Não       3                            Moen, Mr. Sigurd Hansen   Homem  25.00    7.6500            F G73        S
78             79        Sim       2                      Caldwell, Master. Alden Gates   Homem   0.83   29.0000              NaN        S
79             80        Sim       3                           Dowdell, Miss. Elizabeth  Mulher  30.00   12.4750              NaN        S
80             81        Não       3                               Waelens, Mr. Achille   Homem  22.00    9.0000              NaN        S
81             82        Sim       3                        Sheerlinck, Mr. Jan Baptist   Homem  29.00    9.5000              NaN        S
83             84        Não       1                            Carrau, Mr. Francisco M   Homem  28.00   47.1000              NaN        S
84             85        Sim       2                                Ilett, Miss. Bertha  Mulher  17.00   10.5000              NaN        S
85             86        Sim       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  Mulher  33.00   15.8500              NaN        S
86             87        Não       3                             Ford, Mr. William Neal   Homem  16.00   34.3750              NaN        S
88             89        Sim       1                         Fortune, Miss. Mabel Helen  Mulher  23.00  263.0000      C23 C25 C27        S
89             90        Não       3                             Celotti, Mr. Francesco   Homem  24.00    8.0500              NaN        S
90             91        Não       3                               Christmann, Mr. Emil   Homem  29.00    8.0500              NaN        S
91             92        Não       3                         Andreasson, Mr. Paul Edvin   Homem  20.00    7.8542              NaN        S
92             93        Não       1                        Chaffee, Mr. Herbert Fuller   Homem  46.00   61.1750              E31        S
93             94        Não       3                            Dean, Mr. Bertram Frank   Homem  26.00   20.5750              NaN        S
94             95        Não       3                                  Coxon, Mr. Daniel   Homem  59.00    7.2500              NaN        S
96             97        Não       1                          Goldschmidt, Mr. George B   Homem  71.00   34.6542               A5        C
97             98        Sim       1                    Greenfield, Mr. William Bertram   Homem  23.00   63.3583          D10 D12        C
98             99        Sim       2               Doling, Mrs. John T (Ada Julia Bone)  Mulher  34.00   23.0000              NaN        S
99            100        Não       2                                  Kantor, Mr. Sinai   Homem  34.00   26.0000              NaN        S
100           101        Não       3                            Petranec, Miss. Matilda  Mulher  28.00    7.8958              NaN        S
102           103        Não       1                          White, Mr. Richard Frasar   Homem  21.00   77.2875              D26        S
103           104        Não       3                         Johansson, Mr. Gustaf Joel   Homem  33.00    8.6542              NaN        S
104           105        Não       3                     Gustafsson, Mr. Anders Vilhelm   Homem  37.00    7.9250              NaN        S
105           106        Não       3                              Mionoff, Mr. Stoytcho   Homem  28.00    7.8958              NaN        S
106           107        Sim       3                   Salkjelsvik, Miss. Anna Kristine  Mulher  21.00    7.6500              NaN        S
108           109        Não       3                                    Rekic, Mr. Tido   Homem  38.00    7.8958              NaN        S
110           111        Não       1                     Porter, Mr. Walter Chamberlain   Homem  47.00   52.0000             C110        S
111           112        Não       3                               Zabour, Miss. Hileni  Mulher  14.50   14.4542              NaN        C
112           113        Não       3                             Barton, Mr. David John   Homem  22.00    8.0500              NaN        S
113           114        Não       3                            Jussila, Miss. Katriina  Mulher  20.00    9.8250              NaN        S
114           115        Não       3                              Attalah, Miss. Malake  Mulher  17.00   14.4583              NaN        C
115           116        Não       3                              Pekoniemi, Mr. Edvard   Homem  21.00    7.9250              NaN        S
116           117        Não       3                               Connors, Mr. Patrick   Homem  70.50    7.7500              NaN        Q
117           118        Não       2                    Turpin, Mr. William John Robert   Homem  29.00   21.0000              NaN        S
118           119        Não       1                           Baxter, Mr. Quigg Edmond   Homem  24.00  247.5208          B58 B60        C
119           120        Não       3                  Andersson, Miss. Ellis Anna Maria  Mulher   2.00   31.2750              NaN        S
120           121        Não       2                        Hickman, Mr. Stanley George   Homem  21.00   73.5000              NaN        S
122           123        Não       2                               Nasser, Mr. Nicholas   Homem  32.50   30.0708              NaN        C
123           124        Sim       2                                Webber, Miss. Susan  Mulher  32.50   13.0000             E101        S
124           125        Não       1                        White, Mr. Percival Wayland   Homem  54.00   77.2875              D26        S
125           126        Sim       3                       Nicola-Yarred, Master. Elias   Homem  12.00   11.2417              NaN        C
127           128        Sim       3                          Madsen, Mr. Fridtjof Arne   Homem  24.00    7.1417              NaN        S
129           130        Não       3                                 Ekstrom, Mr. Johan   Homem  45.00    6.9750              NaN        S
130           131        Não       3                               Drazenoic, Mr. Jozef   Homem  33.00    7.8958              NaN        C
131           132        Não       3                     Coelho, Mr. Domingos Fernandeo   Homem  20.00    7.0500              NaN        S
132           133        Não       3     Robins, Mrs. Alexander A (Grace Charity Laury)  Mulher  47.00   14.5000              NaN        S
133           134        Sim       2      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  Mulher  29.00   26.0000              NaN        S
134           135        Não       2                     Sobey, Mr. Samuel James Hayden   Homem  25.00   13.0000              NaN        S
135           136        Não       2                                 Richard, Mr. Emile   Homem  23.00   15.0458              NaN        C
136           137        Sim       1                       Newsom, Miss. Helen Monypeny  Mulher  19.00   26.2833              D47        S
137           138        Não       1                        Futrelle, Mr. Jacques Heath   Homem  37.00   53.1000             C123        S
138           139        Não       3                                Osen, Mr. Olaf Elon   Homem  16.00    9.2167              NaN        S
139           140        Não       1                                 Giglio, Mr. Victor   Homem  24.00   79.2000              B86        C
141           142        Sim       3                           Nysten, Miss. Anna Sofia  Mulher  22.00    7.7500              NaN        S
142           143        Sim       3  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  Mulher  24.00   15.8500              NaN        S
143           144        Não       3                                Burke, Mr. Jeremiah   Homem  19.00    6.7500              NaN        Q
144           145        Não       2                         Andrew, Mr. Edgardo Samuel   Homem  18.00   11.5000              NaN        S
145           146        Não       2                       Nicholls, Mr. Joseph Charles   Homem  19.00   36.7500              NaN        S
146           147        Sim       3       Andersson, Mr. August Edvard ("Wennerstrom")   Homem  27.00    7.7958              NaN        S
147           148        Não       3                   Ford, Miss. Robina Maggie "Ruby"  Mulher   9.00   34.3750              NaN        S
148           149        Não       2           Navratil, Mr. Michel ("Louis M Hoffman")   Homem  36.50   26.0000               F2        S
149           150        Não       2                  Byles, Rev. Thomas Roussel Davids   Homem  42.00   13.0000              NaN        S
150           151        Não       2                         Bateman, Rev. Robert James   Homem  51.00   12.5250              NaN        S
151           152        Sim       1                  Pears, Mrs. Thomas (Edith Wearne)  Mulher  22.00   66.6000               C2        S
152           153        Não       3                                   Meo, Mr. Alfonzo   Homem  55.50    8.0500              NaN        S
153           154        Não       3                    van Billiard, Mr. Austin Blyler   Homem  40.50   14.5000              NaN        S
155           156        Não       1                        Williams, Mr. Charles Duane   Homem  51.00   61.3792              NaN        C
156           157        Sim       3                   Gilnagh, Miss. Katherine "Katie"  Mulher  16.00    7.7333              NaN        Q
157           158        Não       3                                    Corn, Mr. Harry   Homem  30.00    8.0500              NaN        S
160           161        Não       3                           Cribb, Mr. John Hatfield   Homem  44.00   16.1000              NaN        S
161           162        Sim       2  Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...  Mulher  40.00   15.7500              NaN        S
162           163        Não       3                         Bengtsson, Mr. John Viktor   Homem  26.00    7.7750              NaN        S
163           164        Não       3                                    Calic, Mr. Jovo   Homem  17.00    8.6625              NaN        S
164           165        Não       3                       Panula, Master. Eino Viljami   Homem   1.00   39.6875              NaN        S
165           166        Sim       3    Goldsmith, Master. Frank John William "Frankie"   Homem   9.00   20.5250              NaN        S
167           168        Não       3    Skoog, Mrs. William (Anna Bernhardina Karlsson)  Mulher  45.00   27.9000              NaN        S
169           170        Não       3                                      Ling, Mr. Lee   Homem  28.00   56.4958              NaN        S
170           171        Não       1                          Van der hoef, Mr. Wyckoff   Homem  61.00   33.5000              B19        S
171           172        Não       3                               Rice, Master. Arthur   Homem   4.00   29.1250              NaN        Q
172           173        Sim       3                       Johnson, Miss. Eleanor Ileen  Mulher   1.00   11.1333              NaN        S
173           174        Não       3                          Sivola, Mr. Antti Wilhelm   Homem  21.00    7.9250              NaN        S
174           175        Não       1                            Smith, Mr. James Clinch   Homem  56.00   30.6958               A7        C
175           176        Não       3                             Klasen, Mr. Klas Albin   Homem  18.00    7.8542              NaN        S

## Adequando o DataSet

### 4 - Uma vez que algumas colunas não serão utilizadas, eventualmente é melhor excluí-las para que não interfiram na análise. Assim, exclua do dataset as colunas Sibsp, Parch e Ticket.

In [39]:
tit.drop(tit.columns[[6,7,8]], axis=1, inplace=True)
tit.head()
len(tit.columns)

9

### 5 - Renomear as colunas restantes para a lingua portuguesa, utilizando os seguintes nomes de colunas: IdPassageiro, Sobreviveu, Classe, Nome, Sexo, Idade, Tarifa, Cabine e Embarque.

In [40]:
header = tit.columns.tolist()
old = header
new = ['IdPassageiro', 'Sobreviveu', 'Classe', 'Nome', 'Sexo', 'Idade', 'Tarifa', 'Cabine', 'Embarque']
tit.rename(columns=dict(zip(old, new)), inplace=True) #rename columns
tit.head()
#tit.columns = ['IdPassageiro', 'Sobreviveu', 'Classe', 'Nome', 'Sexo', 'Idade', 'Tarifa', 'Cabine', 'Embarque']

   IdPassageiro  Sobreviveu  Classe                                               Nome    Sexo  Idade   Tarifa Cabine Embarque
0             1           0       3                            Braund, Mr. Owen Harris    male   22.0   7.2500    NaN        S
1             2           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38.0  71.2833    C85        C
2             3           1       3                             Heikkinen, Miss. Laina  female   26.0   7.9250    NaN        S
3             4           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35.0  53.1000   C123        S
4             5           0       3                           Allen, Mr. William Henry    male   35.0   8.0500    NaN        S

### 6 - Alterar o conteudo da coluna Sobreviveu para:
- 0 => Não
- 1 => Sim

In [41]:
tit.Sobreviveu.replace({0:'Não', 1:'Sim'}, inplace=True)
tit.head()

   IdPassageiro Sobreviveu  Classe                                               Nome    Sexo  Idade   Tarifa Cabine Embarque
0             1        Não       3                            Braund, Mr. Owen Harris    male   22.0   7.2500    NaN        S
1             2        Sim       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38.0  71.2833    C85        C
2             3        Sim       3                             Heikkinen, Miss. Laina  female   26.0   7.9250    NaN        S
3             4        Sim       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35.0  53.1000   C123        S
4             5        Não       3                           Allen, Mr. William Henry    male   35.0   8.0500    NaN        S

### 7 - Alterar o conteudo da coluna Sexo para:
- female => Mulher
- male   => Homem

In [42]:
tit.Sexo.replace({'female':'Mulher', 'male':'Homem'}, inplace=True)
tit.head()

   IdPassageiro Sobreviveu  Classe                                               Nome    Sexo  Idade   Tarifa Cabine Embarque
0             1        Não       3                            Braund, Mr. Owen Harris   Homem   22.0   7.2500    NaN        S
1             2        Sim       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  Mulher   38.0  71.2833    C85        C
2             3        Sim       3                             Heikkinen, Miss. Laina  Mulher   26.0   7.9250    NaN        S
3             4        Sim       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  Mulher   35.0  53.1000   C123        S
4             5        Não       3                           Allen, Mr. William Henry   Homem   35.0   8.0500    NaN        S

## Alguns números

### 8 - Quantas mulheres e quantos homems estavam à bordo, de acordo com o dataset?

In [43]:
tit.Sexo.value_counts()

Homem     577
Mulher    314
Name: Sexo, dtype: int64

### 9 - Quantos passageiros sobreviveram e quantos não sobreviveram?

In [44]:
tit.Sobreviveu.value_counts()

Não    549
Sim    342
Name: Sobreviveu, dtype: int64

### 10 - Quantas mulheres não sobreviveram?

In [45]:
tit[(tit.Sexo=='Mulher') & (tit.Sobreviveu=='Não')].Sexo.value_counts()

Mulher    81
Name: Sexo, dtype: int64

### 11 - Proporcionalmente, sobreviveram mais homens ou mais mulheres? Cite as proporções.

In [46]:
pd.crosstab(tit['Sobreviveu'],tit['Sexo']).apply(lambda p: p/p.sum(), axis=1)*100 #percentual

Sexo            Homem     Mulher
Sobreviveu
Não         85.245902  14.754098
Sim         31.871345  68.128655

### 12 - Levando-se em consideração a idade dos passageiros, qual a idade e quantidade de pessoas com o maior número de mortos?

In [61]:
tit[(tit.Sobreviveu=='Não')].dropna(subset=['Idade']).Idade.value_counts().nlargest(1)
#import csv
#tit_2 = tit.stack().str.split('\t', expand=True).unstack()
#tit_2.to_csv('teste_tit.csv', sep="\t", quoting=csv.QUOTE_NONE)

21.0    19
Name: Idade, dtype: int64

### 13 - Qual a média de idade dos homens sobreviventes?

In [63]:
tit[(tit.Sobreviveu=='Sim') & (tit.Sexo=='Homem')].Idade.mean()

27.276021505376345

### 14 - Levando-se em consideração passageiros prioritários (mulheres e crianças de até 15 anos independente do sexo) qual a proporção de sobreviventes por sexo?

In [68]:
tit[((tit.Sexo=='Mulher') | (tit.Idade<=15)) & (tit.Sobreviveu=='Sim')].Sexo.value_counts(normalize=True)*100

Mulher    91.732283
Homem      8.267717
Name: Sexo, dtype: float64

### 15 - Qual a quantidade de passageiros por classe?

In [69]:
tit.groupby('Classe').size()

Classe
1    216
2    184
3    491
dtype: int64

### 16 - Qual o percentual de sobreviventes por classe?

In [77]:
pd.crosstab(tit['Sobreviveu'],tit['Classe']).apply(lambda p: p/p.sum(), axis=1)*100 #percentual

Classe              1          2          3
Sobreviveu
Não         14.571949  17.668488  67.759563
Sim         39.766082  25.438596  34.795322

### 17 - Crie um dataframe que demonstre a quantidade de sobreviventes e não sobreviventes, agrupados por sexo e classe.

In [90]:
qtd = pd.DataFrame({'qtd':tit.groupby(['Sexo','Classe','Sobreviveu']).size()}).reset_index()
qtd

      Sexo  Classe Sobreviveu  qtd
0    Homem       1        Não   77
1    Homem       1        Sim   45
2    Homem       2        Não   91
3    Homem       2        Sim   17
4    Homem       3        Não  300
5    Homem       3        Sim   47
6   Mulher       1        Não    3
7   Mulher       1        Sim   91
8   Mulher       2        Não    6
9   Mulher       2        Sim   70
10  Mulher       3        Não   72
11  Mulher       3        Sim   72

### 18 - Dos homens com idade entre 24 e 30 anos quantos da classe 3 sobreviveram? Quantos da classe 2 não sobreviveram?

In [124]:
H = tit.Sexo == 'Homem'
Age24 = tit.Idade >= 24 
Age30 = tit.Idade <= 30
C2 = tit.Classe == 2
C3 = tit.Classe == 3
S = tit.Sobreviveu == 'Sim'
N = tit.Sobreviveu == 'Não'
tit[( Age24 & Age30) & ((C3 & S) | (C2 & N))].Classe.value_counts()

2    27
3    22
Name: Classe, dtype: int64

### Extra shot (1 ponto adicional): Calcule a probabilidade condicional de uma pessoa sobreviver, dado seu sexo e a classe em que estava viajando:
- P(S= true | G=female,C=1)
- P(S= true | G=female,C=2)
- P(S= true | G=female,C=3)
- P(S= true | G=male,C=1)
- P(S= true | G=male,C=2)
- P(S= true | G=male,C=3)